<?php
$pageDefinitions = [
    'customers'=>['All Customers','Customers',['Customer Name','Type','Mobile','Email','Address','Vehicles','Outstanding','Status','Actions'],['Total Customers','Individual Customers','Company Customers','Total Outstanding']],
    'vehicles'=>['All Vehicles','Vehicles',['Vehicle Number','Customer Name','Make / Brand','Model','Engine Number','Chassis Number','Colour','Current Mileage','Status','Actions'],['Total Vehicles','Active Vehicles','Vehicles In Service']],
    'jobcards-new'=>['New Job Card','Job Cards',[],[]], 'jobcards-pending'=>['Pending Job Cards','Job Cards',['Customer','Vehicle','Date','Complaint','Status','Action'],[]], 'jobcards-ongoing'=>['Ongoing Job Cards','Job Cards',['Customer','Vehicle','Date','Parts Used','Status','Action'],[]], 'jobcards-completed'=>['Completed Job Cards','Job Cards',['Customer','Vehicle','Completed Date','Parts Used','Status','Action'],[]],
    'appointments'=>['Appointments','Appointments',['Appointment No','Customer','Vehicle','Mobile','Date & Time','Requested Service','Status','Actions'],['Appointments Today','Pending','Confirmed']], 'estimates'=>['Estimates','Estimates',['Estimate No','Customer','Vehicle','Date','Estimated Total','Status','Actions'],[]], 'invoices'=>['Invoices','Invoices',['Invoice No','Customer','Vehicle','Invoice Date','Grand Total','Paid','Due','Status','Actions'],[]], 'payments'=>['Payments','Payments',['Payment Date','Invoice No','Customer','Payment Method','Amount','Status','Reference','Actions'],['Total Received','Cash Received','Card Received','Outstanding']], 'expenses'=>['Expenses','Expenses',['Expense No','Date','Category','Description','Payment Method','Amount','Status','Actions'],['Total Expenses','This Month','This Week']],
    'stock'=>['Stock List','Stock / Parts',['Part Code','Part Name','Category','Brand','Buying Price','Selling Price','Available Qty','Low Stock Level','Status','Action'],['Total Items','In Stock','Low Stock Items','Out of Stock']], 'stock-purchases'=>['Stock Purchases','Stock / Parts',['Purchase No','Supplier','Date','Items','Total','Status','Actions'],[]], 'stock-low'=>['Low Stock','Stock / Parts',['Part Code','Part Name','Available Qty','Reorder Level','Status','Action'],['Low Stock Items','Out of Stock']],
    'services'=>['Services','Services',['Service Code','Service Name','Category','Description','Price','Duration','Status','View'],['Total Services','Active','Inactive']], 'suppliers'=>['Suppliers','Suppliers',['Supplier Name','Contact Person','Phone','Email','Status','Purchases','Outstanding','Actions'],[]],
    'employees'=>['Employee List','Employees',['Employee ID','Name','Phone','Role / Position','Join Date','Salary','Status','Actions'],[]], 'employees-salary'=>['Salary Management','Employees',['Employee','Period','Basic Salary','Allowances','Deductions','Net Salary','Status','Actions'],[]], 'employees-advances'=>['Staff Advances','Employees',['Employee','Date','Amount','Reason','Status','Actions'],[]], 'employees-loans'=>['Staff Loans','Employees',['Employee','Date','Amount','Installment','Balance','Status','Actions'],[]], 'other-income'=>['Other Income','Other Income',['Date','Category / Source','Description','Amount','Payment Method','Reference','Received By','Actions'],['Total Other Income']], 'bays'=>['Bay Management','Bay Management',['Bay Name / Number','Status','Current Job Card','Vehicle','Assigned Information','Actions'],['Total Bays','Available','Occupied','Maintenance']],
];
$forms = ['customers-add'=>['Add Customer',['Customer Type'=>'select:Individual|Company','Customer / Company Name'=>'text','Mobile Number'=>'text','Secondary Mobile Number'=>'text','Email Address'=>'email','NIC / Registration Number'=>'text','Address'=>'textarea','Notes'=>'textarea']], 'vehicles-add'=>['Add Vehicle',['Select Customer'=>'select:Select customer','Vehicle Number'=>'text','Vehicle Type'=>'text','Make / Brand'=>'text','Model'=>'text','Engine Number'=>'text','Chassis Number'=>'text','Colour'=>'text','Current Mileage'=>'number','Notes'=>'textarea']], 'stock-add'=>['Add New Stock Item',['Part Code'=>'text','Part Name'=>'text','Category'=>'text','Brand'=>'text','Buying Price'=>'number','Selling Price'=>'number','Opening Quantity'=>'number','Low Stock Alert Level / Reorder Level'=>'number','Supplier'=>'text','Location'=>'text','Description'=>'textarea','Status'=>'select:Active|Inactive']], 'employees-add'=>['Add Employee',['Name'=>'text','Phone'=>'text','Role / Position'=>'text','Join Date'=>'date','Salary'=>'number','Status'=>'select:Active|Inactive']]];
$forms += [
    'jobcards-new'=>['New Job Card',['Vehicle Number'=>'text','Customer Information'=>'text','Complaint / Requested Work'=>'textarea','Notes'=>'textarea','Date'=>'date','Job Status'=>'select:Pending|Start Job']],
    'appointments-add'=>['New Appointment',['Customer'=>'text','Phone'=>'text','Vehicle Number'=>'text','Vehicle / Model'=>'text','Appointment Date'=>'date','Appointment Time'=>'time','Requested Service'=>'text','Notes'=>'textarea']],
    'estimates-add'=>['Create Estimate',['Customer'=>'text','Vehicle'=>'text','Estimate Date'=>'date','Items / Parts'=>'textarea','Quantity'=>'number','Price'=>'number','Special Service Charge'=>'number','Special Discount'=>'number']],
    'invoices-add'=>['Create Invoice',['Invoice Number'=>'text','Invoice Date'=>'date','Due Date'=>'date','Customer'=>'text','Vehicle (optional)'=>'text','Invoice Items'=>'textarea','Quantity'=>'number','Unit Price'=>'number','Special Service Charge'=>'number','Special Discount'=>'number','Payment Method'=>'select:Cash|Card']],
    'expenses-add'=>['New Expense',['Expense Number'=>'text','Date'=>'date','Category'=>'text','Description'=>'textarea','Supplier / Vendor'=>'text','Payment Method'=>'select:Cash|Card|Bank Transfer','Amount'=>'number','Reference'=>'text','Notes'=>'textarea']],
    'other-income-add'=>['Add Other Income',['Date'=>'date','Category / Source'=>'text','Description'=>'textarea','Amount'=>'number','Payment Method'=>'select:Cash|Card|Bank Transfer','Reference'=>'text','Notes'=>'textarea','Received By'=>'text']],
];
$labels = ['jobcards-new'=>'New Job Card','appointments'=>'Appointments','appointments-add'=>'Add Appointment','estimates'=>'Estimates','estimates-add'=>'Create Estimate','invoices'=>'Invoices','invoices-add'=>'Create Invoice','payments'=>'Payments','expenses'=>'Expenses','expenses-add'=>'New Expense','stock-purchases'=>'Stock Purchases','stock-low'=>'Low Stock','services'=>'Services','suppliers'=>'Suppliers','other-income'=>'Other Income','other-income-add'=>'Add Other Income','bays'=>'Bay Management','reports-daily'=>'Daily Summary','reports-gross-profit'=>'Daily Gross Profit','reports-monthly'=>'Monthly Summary','reports-sales'=>'Sales Report','reports-payment'=>'Payment Report','reports-expense'=>'Expense Report','reports-other-income'=>'Other Income Report','reports-stock'=>'Stock Report','reports-parts-purchase'=>'Parts Purchase Report','reports-internal-external'=>'Internal vs External Parts Report','reports-parts-profit'=>'Spare Parts Profit Report','reports-discount'=>'Job Wise Discount Report','reports-outstanding'=>'Customer Outstanding Report','reports-employee'=>'Employee Report','reports-net-profit'=>'Net Profit Report','settings-password'=>'Change Password'];
$reportSections = array_filter($labels, fn($key) => str_starts_with($key, 'reports-'), ARRAY_FILTER_USE_KEY);
$addRoutes = ['customers'=>'customers-add','vehicles'=>'vehicles-add','appointments'=>'appointments-add','estimates'=>'estimates-add','invoices'=>'invoices-add','expenses'=>'expenses-add','stock'=>'stock-add','employees'=>'employees-add','other-income'=>'other-income-add'];
$sectionTitle = $pageDefinitions[$section][0] ?? $forms[$section][0] ?? ($reportSections[$section] ?? ($labels[$section] ?? 'Administrator Dashboard'));
function admin_kpi(string $label): void { echo '<div class="col-sm-6 col-xl-3"><div class="admin-kpi"><span>'.e($label).'</span><strong>0</strong></div></div>'; }
function admin_empty(string $message = 'No records found yet. Data will appear here when this module is connected.'): void { echo '<tr><td colspan="20" class="empty-table">'.e($message).'</td></tr>'; }
require __DIR__ . '/../includes/header.php';
if ($section === 'dashboard') {
    $dashboard = admin_dashboard_data((string) ($_GET['period'] ?? 'today'));
    require __DIR__ . '/admin-dashboard.php';
    require __DIR__ . '/../includes/footer.php';
    exit;
}
?><div class="admin-page-heading"><div><div class="breadcrumb-line">Admin / <?= e($sectionTitle) ?></div><h1><?= e($sectionTitle) ?></h1><p>Manage your workshop operations from one place.</p></div><?php if (isset($forms[$section])): ?><a href="#admin-form" class="btn btn-danger">+ <?= e($sectionTitle) ?></a><?php elseif (isset($pageDefinitions[$section])): ?><a href="index.php?page=admin&amp;section=<?= e($addRoutes[$section] ?? 'dashboard') ?>" class="btn btn-danger">+ Add</a><?php endif; ?></div>
<?php if ($section === 'dashboard'): ?><div class="row g-3 admin-kpi-row"><?php foreach (['Total Customers','Total Vehicles','Total Job Cards','Today\'s Appointments','Unpaid Invoices'] as $k): admin_kpi($k); endforeach; ?></div><div class="row g-4 mt-1"><div class="col-xl-8"><div class="admin-panel"><div class="panel-heading"><h2>Today's Overview</h2><span class="muted-label"><?= date('d M Y') ?></span></div><div class="row g-3 overview-grid"><?php foreach (['Today\'s Job Cards','In Progress','Completed Today','Pending Payments','Today\'s Revenue'] as $k): ?><div class="col-sm-6 col-lg"><div class="overview-stat"><span><?= e($k) ?></span><strong>0</strong></div></div><?php endforeach; ?></div></div><div class="admin-panel mt-4"><div class="panel-heading"><h2>Daily Revenue Overview</h2><span class="muted-label">No revenue data</span></div><div class="chart-placeholder"><div class="chart-line"></div><span>Revenue chart will appear after invoices and payments are connected.</span></div></div></div><div class="col-xl-4"><div class="admin-panel h-100"><div class="panel-heading"><h2>Income Summary</h2></div><div class="donut-placeholder"><div class="donut">0%</div></div><p class="empty-note text-center">No income recorded yet.</p></div></div></div><div class="row g-3 mt-1"><?php foreach (['Gross Profit (Today)','Expenses (Today)','Other Income (Today)','Net Profit (Today)'] as $k): admin_kpi($k); endforeach; ?></div><div class="row g-4 mt-1"><div class="col-lg-7"><div class="admin-panel"><div class="panel-heading"><h2>Recent Job Cards</h2><a href="index.php?page=admin&amp;section=jobcards-pending">View all</a></div><table class="table admin-table"><thead><tr><th>Customer</th><th>Vehicle</th><th>Status</th></tr></thead><tbody><?php admin_empty(); ?></tbody></table></div></div><div class="col-lg-5"><div class="admin-panel"><div class="panel-heading"><h2>Low Stock Alerts</h2><a href="index.php?page=admin&amp;section=stock-low">View all</a></div><table class="table admin-table"><thead><tr><th>Part</th><th>Available</th><th>Status</th></tr></thead><tbody><?php admin_empty('No low stock alerts.'); ?></tbody></table></div></div></div><div class="admin-panel mt-4"><div class="panel-heading"><h2>Quick Actions</h2></div><div class="quick-actions"><?php foreach ([['Add Customer','customers-add'],['Add Vehicle','vehicles-add'],['New Job Card','jobcards-new'],['New Estimate','estimates'],['New Invoice','invoices'],['Add Expense','expenses'],['Add Stock / Part','stock-add']] as $action): ?><a class="quick-action" href="index.php?page=admin&amp;section=<?= e($action[1]) ?>"><?= e($action[0]) ?></a><?php endforeach; ?></div></div>
<?php elseif (isset($forms[$section])): ?><div id="admin-form" class="admin-panel admin-form"><h2><?= e($forms[$section][0]) ?></h2><p class="empty-note">This form is ready for backend integration. No record will be saved until its module iteration is implemented.</p><form><div class="row g-3"><?php foreach ($forms[$section][1] as $label => $type): ?><div class="col-md-6 <?= str_contains($type, 'textarea') ? 'col-md-12' : '' ?>"><label class="form-label"><?= e($label) ?></label><?php if (str_starts_with($type, 'select:')): ?><select class="form-select"><option><?= e(explode('|', substr($type, 7))[0]) ?></option><?php foreach (array_slice(explode('|', substr($type, 7)), 1) as $option): ?><option><?= e($option) ?></option><?php endforeach; ?></select><?php elseif ($type === 'textarea'): ?><textarea class="form-control" rows="3"></textarea><?php else: ?><input class="form-control" type="<?= e($type) ?>" <?= $type === 'number' ? 'min="0" step="0.01"' : '' ?>><?php endif; ?></div><?php endforeach; ?></div><button type="button" class="btn btn-danger mt-4" disabled>Save when backend is connected</button></form></div>
<?php elseif (isset($pageDefinitions[$section])): [$heading, $group, $columns, $kpis] = $pageDefinitions[$section]; if ($kpis): ?><div class="row g-3 admin-kpi-row"><?php foreach ($kpis as $k): admin_kpi($k); endforeach; ?></div><?php endif; ?><div class="admin-panel mt-4"><div class="filter-bar"><input class="form-control" placeholder="Search <?= e($heading) ?>"><select class="form-select"><option>All statuses</option></select><button class="btn btn-primary">Filter</button></div><div class="table-responsive"><table class="table admin-table"><thead><tr><?php foreach ($columns as $column): ?><th><?= e($column) ?></th><?php endforeach; ?></tr></thead><tbody><?php admin_empty(); ?></tbody></table></div><div class="empty-note">Pagination will be enabled when this module has a backend data source.</div></div>
<?php elseif (str_starts_with($section, 'reports-')): ?><div class="row g-3 admin-kpi-row"><?php foreach (['Total Sales','Spare Parts Sales','Parts Cost','Gross Profit','Total Expenses','Other Income','Net Profit'] as $k): admin_kpi($k); endforeach; ?></div><div class="row g-4 mt-1"><div class="col-lg-7"><div class="admin-panel"><div class="panel-heading"><h2>Financial Summary</h2></div><div class="chart-placeholder"><span>Report data will appear after financial modules are connected.</span></div></div></div><div class="col-lg-5"><div class="admin-panel"><div class="panel-heading"><h2>Breakdown</h2></div><p class="empty-note">No report data available yet.</p></div></div></div><div class="admin-panel mt-4"><div class="filter-bar"><input class="form-control" type="date"><input class="form-control" type="date"><button class="btn btn-primary">Apply dates</button></div><div class="empty-state"><strong>No report data</strong><span>Reports are prepared for backend integration in later iterations.</span></div></div>
<?php else: ?><div class="admin-panel"><div class="empty-state"><strong><?= e($sectionTitle) ?></strong><span>This Admin screen is available and ready for its backend iteration.</span></div></div><?php endif; ?><?php require __DIR__ . '/../includes/footer.php'; ?>
