<div class="admin-page-heading"><div><div class="breadcrumb-line">Finance / Cashier Handovers</div><h1>Cashier Handovers</h1><p>Review cash drawers handed over by cashiers and confirm the amount received.</p></div></div>
<?php if ($errors): ?><div class="alert alert-danger"><?php foreach ($errors as $error): ?><div><?= e($error) ?></div><?php endforeach; ?></div><?php endif; ?>
<div class="admin-panel mb-4"><form method="get" class="filter-bar"><input type="hidden" name="page" value="admin"><input type="hidden" name="section" value="cashier-handovers"><input class="form-control" type="search" name="search" value="<?= e($search) ?>" placeholder="Search cashier or date"><select class="form-select" name="handover_status"><option value="">All statuses</option><option value="pending" <?= $statusFilter === 'pending' ? 'selected' : '' ?>>Pending</option><option value="accepted" <?= $statusFilter === 'accepted' ? 'selected' : '' ?>>Accepted</option><option value="rejected" <?= $statusFilter === 'rejected' ? 'selected' : '' ?>>Rejected</option></select><select class="form-select" name="balance_filter"><option value="">All balances</option><option value="due" <?= $balanceFilter === 'due' ? 'selected' : '' ?>>Due balance</option><option value="balanced" <?= $balanceFilter === 'balanced' ? 'selected' : '' ?>>Balanced</option></select><input class="form-control" type="date" name="from" value="<?= e($from) ?>"><input class="form-control" type="date" name="to" value="<?= e($to) ?>"><button class="btn btn-primary" type="submit">Filter</button><a class="btn btn-light" href="index.php?page=admin&amp;section=cashier-handovers">Reset</a></form></div>
<div class="admin-panel"><div class="panel-heading"><h2>Handover History</h2><span class="muted-label"><?= count($rows) ?> record(s)</span></div><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Date</th><th>Cashier</th><th>Expected</th><th>Handed Over</th><th>Received</th><th>Balance / Difference</th><th>Status</th><th>Action</th></tr></thead><tbody><?php if (!$rows): ?><tr><td colspan="8" class="empty-table">No cashier handover records found.</td></tr><?php else: foreach ($rows as $row): ?><tr><td><?= e($row['register_date']) ?></td><td><?= e($row['cashier_name']) ?></td><td>Rs. <?= number_format((float) $row['expected_closing_amount'], 2) ?></td><td>Rs. <?= number_format((float) $row['handover_amount'], 2) ?></td><td><?= $row['accepted_amount'] === null ? '-' : 'Rs. '.number_format((float) $row['accepted_amount'], 2) ?></td><td class="<?= $row['balance_amount'] > 0 ? 'text-danger' : 'text-success' ?>"><?= $row['balance_amount'] > 0 ? 'Due Rs. '.number_format($row['balance_amount'], 2) : 'Balanced' ?></td><td><span class="status-badge <?= $row['handover_status'] === 'accepted' ? 'status-success' : ($row['handover_status'] === 'rejected' ? 'status-danger' : 'status-warning') ?>"><?= e($row['handover_status'] === 'accepted' ? 'Accepted' : ($row['handover_status'] === 'rejected' ? 'Rejected' : 'Pending acceptance')) ?></span></td><td><?php if ($row['handover_status'] === 'pending'): ?><form method="post" class="handover-accept-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="handover_action" value="accept"><input type="hidden" name="register_id" value="<?= (int) $row['id'] ?>"><input class="form-control form-control-sm" type="number" name="accepted_amount" min="0" step="0.01" value="<?= e((string) $row['handover_amount']) ?>" required><input class="form-control form-control-sm" type="text" name="acceptance_note" placeholder="Note (optional)"><button class="btn btn-success btn-sm" type="submit">Accept Cash</button></form><?php else: ?><span class="muted-label"><?= e((string) ($row['accepted_by_name'] ?? '-')) ?><br><?= e((string) ($row['accepted_at'] ?? '')) ?></span><?php endif; ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
<?php require __DIR__ . '/../includes/footer.php'; ?>
<script>
document.querySelectorAll('.handover-accept-form').forEach(function (form) {
    const hidden = form.querySelector('input[name="handover_action"]');
    if (hidden) hidden.remove();
    const accept = form.querySelector('button[type="submit"]');
    if (accept) { accept.name = 'handover_action'; accept.value = 'accept'; }
    const reject = document.createElement('button');
    reject.type = 'submit'; reject.name = 'handover_action'; reject.value = 'reject';
    reject.className = 'btn btn-outline-danger btn-sm'; reject.textContent = 'Not Accept';
    form.appendChild(reject);
});
</script>
