<?php
require __DIR__ . '/../includes/header.php';
$firstName = strtok($user['name'], ' ');
$register = $cashierDashboard['register'];
$handoverStatus = $register['handover_status'] ?? 'not_submitted';
$handoverLabel = $register && ($register['status'] ?? '') === 'open' ? 'Drawer open' : (['not_submitted' => 'Not started', 'pending' => 'Waiting for admin', 'accepted' => 'Accepted', 'rejected' => 'Needs resubmission'][$handoverStatus] ?? 'Not started');
$drawerActionLabel = $register && ($register['status'] ?? '') === 'open' ? 'Close & Handover' : 'Open Daily Cash Drawer';
$handoverClass = $handoverStatus === 'accepted' ? 'is-success' : ($handoverStatus === 'rejected' ? 'is-danger' : ($handoverStatus === 'pending' ? 'is-warning' : 'is-info'));
$cashPosition = (float) ($register['opening_amount'] ?? 0) + $cashierDashboard['sales'] + $cashierDashboard['income'] - $cashierDashboard['expenses'] - $cashierDashboard['advances'];
?>
<main class="cashier-dashboard">
    <section class="cashier-welcome"><div><span class="eyebrow">Front desk command center</span><h1>Good day, <?= e($firstName) ?>.</h1><p>Keep the counter moving, keep the cash clear.</p></div><div class="cashier-date"><span><?= e(date('l')) ?></span><strong><?= e(date('d M Y')) ?></strong></div></section>
    <?php if ($handoverStatus === 'rejected'): ?><div class="cashier-alert is-danger"><strong>Handover needs attention.</strong><span>Admin rejected the previous count. Recount your drawer and submit it again.</span><a href="index.php?page=admin&amp;section=cashier-register">Review drawer</a></div><?php elseif ($handoverStatus === 'pending'): ?><div class="cashier-alert is-warning"><strong>Cash handover is pending.</strong><span>Your closing amount is waiting for admin acceptance.</span><a href="index.php?page=admin&amp;section=cashier-register">View status</a></div><?php endif; ?>
    <section class="cashier-hero-card"><div class="cashier-hero-copy"><span class="eyebrow">Today's cash runway</span><h2>Rs. <?= number_format($cashPosition, 2) ?></h2><p>Estimated cash position after today's sales, income, expenses and advances.</p><a class="cashier-primary-action" href="index.php?page=admin&amp;section=cashier-register">Open Daily Cash Drawer <span>-&gt;</span></a></div><div class="cashier-hero-orbit"><span class="orbit-ring"></span><span class="orbit-ring orbit-ring-two"></span><strong><?= $register ? e($handoverLabel) : 'Drawer not opened' ?></strong><small>Handover status</small></div></section>
    <section class="cashier-metrics"><a class="cashier-metric metric-blue" href="index.php?page=admin&amp;section=invoices-mine"><span class="metric-mark">Rs</span><small>Today's sales</small><strong>Rs. <?= number_format($cashierDashboard['sales'], 2) ?></strong><em><?= $cashierDashboard['invoice_count'] ?> invoice<?= $cashierDashboard['invoice_count'] === 1 ? '' : 's' ?></em></a><a class="cashier-metric metric-green" href="index.php?page=admin&amp;section=invoices-mine"><span class="metric-mark">OK</span><small>Payments received</small><strong>Rs. <?= number_format($cashierDashboard['payment_total'], 2) ?></strong><em><?= $cashierDashboard['payment_count'] ?> payment<?= $cashierDashboard['payment_count'] === 1 ? '' : 's' ?> posted today</em></a><a class="cashier-metric metric-orange" href="index.php?page=admin&amp;section=invoices-mine"><span class="metric-mark">Due</span><small>Outstanding balance</small><strong>Rs. <?= number_format($cashierDashboard['due'], 2) ?></strong><em>your invoice balance</em></a><a class="cashier-metric metric-purple" href="index.php?page=admin&amp;section=jobcards-pending"><span class="metric-mark">JOB</span><small>Open job cards</small><strong><?= number_format($cashierDashboard['open_jobs']) ?></strong><em><?= $cashierDashboard['jobs_today'] ?> created today</em></a></section>
    <section class="cashier-work-grid"><article class="cashier-panel cashier-handover-panel"><div class="cashier-panel-heading"><div><span class="eyebrow">End of day</span><h2>Cash handover</h2></div><span class="cashier-status <?= e($handoverClass) ?>"><?= e($handoverLabel) ?></span></div><div class="handover-amount"><span>Expected handover</span><strong>Rs. <?= number_format($cashierDashboard['expected'], 2) ?></strong></div><div class="handover-steps"><div class="handover-step <?= $register ? 'is-done' : '' ?>"><b>1</b><span>Open drawer</span></div><div class="handover-step <?= $register && $handoverStatus !== 'not_submitted' ? 'is-done' : '' ?>"><b>2</b><span>Count &amp; close</span></div><div class="handover-step <?= $handoverStatus === 'accepted' ? 'is-done' : '' ?>"><b>3</b><span>Admin accepts</span></div></div><a class="cashier-outline-action" href="index.php?page=admin&amp;section=cashier-register">Go to cash drawer <span>-&gt;</span></a></article><article class="cashier-panel cashier-today-panel"><div class="cashier-panel-heading"><div><span class="eyebrow">Live counter</span><h2>Today's pulse</h2></div><span class="pulse-dot">Live</span></div><div class="pulse-list"><div><span>Job cards created</span><strong><?= $cashierDashboard['jobs_today'] ?></strong></div><div><span>Completed jobs today</span><strong><?= $cashierDashboard['completed_jobs'] ?></strong></div><div><span>Other income</span><strong>Rs. <?= number_format($cashierDashboard['income'], 2) ?></strong></div><div><span>Expenses + advances</span><strong class="text-danger">Rs. <?= number_format($cashierDashboard['expenses'] + $cashierDashboard['advances'], 2) ?></strong></div></div></article></section>
    <section class="cashier-bottom-grid"><article class="cashier-panel cashier-quick-panel"><div class="cashier-panel-heading"><div><span class="eyebrow">Shortcuts</span><h2>What do you need?</h2></div></div><div class="cashier-shortcuts"><a href="index.php?page=admin&amp;section=invoices-quick"><b>+</b><span>New invoice</span></a><a href="index.php?page=admin&amp;section=other-income-add"><b>+</b><span>Add income</span></a><a href="index.php?page=admin&amp;section=expenses-add"><b>+</b><span>Add expense</span></a><a href="index.php?page=admin&amp;section=invoices-mine"><b>&gt;</b><span>My invoices</span></a></div></article><article class="cashier-panel cashier-recent-panel"><div class="cashier-panel-heading"><div><span class="eyebrow">Your latest work</span><h2>Recent invoices</h2></div><a href="index.php?page=admin&amp;section=invoices-mine">View all</a></div><div class="cashier-recent-list"><?php if (!$cashierDashboard['recent_invoices']): ?><p class="cashier-empty">No invoices created yet.</p><?php else: foreach ($cashierDashboard['recent_invoices'] as $invoice): ?><div><span><strong><?= e($invoice['invoice_no']) ?></strong><small><?= e($invoice['customer_name']) ?></small></span><b>Rs. <?= number_format((float) $invoice['total_amount'], 2) ?></b><em class="cashier-status <?= e($invoice['payment_status'] === 'paid' ? 'is-success' : 'is-warning') ?>"><?= e(ucfirst($invoice['payment_status'])) ?></em></div><?php endforeach; endif; ?></div></article></section>
</main>
<?php require __DIR__ . '/../includes/footer.php'; ?>
<?php if ($register && ($register['status'] ?? '') === 'open'): ?><script>(function(){const action=document.querySelector('.cashier-primary-action');if(action&&action.firstChild)action.firstChild.textContent='Close & Handover ';})();</script><?php endif; ?>
