<?php require __DIR__ . '/../includes/header.php'; ?>
<div class="admin-page-heading">
    <div><div class="breadcrumb-line">Cashier / Daily Cash Drawer</div><h1>Daily Cash Drawer</h1><p>Record the morning float, track cash movement, and reconcile the drawer at closing.</p></div>
</div>

<?php if ($errors): ?><div class="alert alert-danger"><?php foreach ($errors as $error): ?><div><?= e($error) ?></div><?php endforeach; ?></div><?php endif; ?>
<?php if (($record['handover_status'] ?? '') === 'rejected'): ?><div class="alert alert-warning"><strong>Admin did not accept this cash handover.</strong> Please recount the cash and submit the corrected closing amount again.<?php if (!empty($record['acceptance_note'])): ?><br><?= e($record['acceptance_note']) ?><?php endif; ?></div><?php endif; ?>

<div class="admin-panel mb-4">
    <form method="get" class="filter-bar">
        <input type="hidden" name="page" value="admin"><input type="hidden" name="section" value="cashier-register">
        <label class="form-label mb-0">Register date</label><input class="form-control" type="date" name="register_date" value="<?= e($date) ?>" max="<?= e(date('Y-m-d')) ?>">
        <button class="btn btn-primary" type="submit">View day</button>
    </form>
</div>

<?php if (!$record): ?>
    <div class="admin-panel register-open-panel">
        <div class="panel-heading"><div><h2>Open Today's Cash Drawer</h2><p class="empty-note">Enter the cash already in the drawer before starting today's work.</p></div><span class="status-badge status-pending">Not opened</span></div>
        <form method="post" class="row g-3">
            <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="register_action" value="open"><input type="hidden" name="register_date" value="<?= e($date) ?>">
            <div class="col-md-4"><label class="form-label">Opening cash (Rs.)</label><input class="form-control" type="number" name="opening_amount" min="0" step="0.01" required></div>
            <div class="col-md-8"><label class="form-label">Opening note</label><input class="form-control" type="text" name="notes" placeholder="Optional note about the opening float"></div>
            <div class="col-12"><button class="btn btn-danger" type="submit">Open Cash Drawer</button></div>
        </form>
    </div>
<?php else: ?>
    <div class="row g-3 admin-kpi-row">
        <?php foreach ([['Opening cash', $record['opening_amount'], 'primary'], ['Cash sales', $totals['sales'], 'success'], ['Other cash income', $totals['income'], 'info'], ['Cash expenses + advances', $totals['expenses'] + $totals['advances'], 'danger'], ['Expected closing cash', $totals['expected'], 'warning']] as $card): ?><div class="col-sm-6 col-xl"><div class="admin-kpi register-kpi <?= e($card[2]) ?>"><span><?= e($card[0]) ?></span><strong>Rs. <?= number_format((float) $card[1], 2) ?></strong></div></div><?php endforeach; ?>
    </div>
    <div class="admin-panel mt-4">
        <div class="panel-heading"><div><h2>Drawer Reconciliation</h2><p class="empty-note">Expected cash = opening cash + cash received - cash paid out.</p></div><span class="status-badge <?= $record['status'] === 'closed' ? 'status-success' : 'status-warning' ?>"><?= e(ucfirst($record['status'])) ?></span></div>
        <?php if ($record['status'] === 'open' && in_array($record['handover_status'] ?? 'not_submitted', ['not_submitted', 'rejected'], true)): ?>
            <form method="post" class="row g-3 align-items-end"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="register_action" value="close"><input type="hidden" name="register_date" value="<?= e($date) ?>"><div class="col-md-4"><label class="form-label">Actual closing cash (Rs.)</label><input class="form-control" type="number" name="actual_closing_amount" min="0" step="0.01" required></div><div class="col-md-5"><label class="form-label">Closing note</label><input class="form-control" type="text" name="notes" placeholder="Optional reconciliation note"></div><div class="col-md-3"><button class="btn btn-danger w-100" type="submit">Close &amp; Reconcile</button></div></form>
        <?php elseif (($record['handover_status'] ?? '') === 'pending'): ?><div class="row g-3"><div class="col-md-4"><span class="muted-label">Cash submitted</span><strong class="d-block fs-4">Rs. <?= number_format((float) $record['handover_amount'], 2) ?></strong></div><div class="col-md-8"><span class="muted-label">Status</span><strong class="d-block fs-5 text-warning">Waiting for admin acceptance. The register is not closed yet.</strong></div></div><?php else: ?><div class="row g-3"><div class="col-md-4"><span class="muted-label">Actual closing cash</span><strong class="d-block fs-4">Rs. <?= number_format((float) $record['actual_closing_amount'], 2) ?></strong></div><div class="col-md-4"><span class="muted-label">Difference</span><strong class="d-block fs-4 <?= (float) $record['difference_amount'] < 0 ? 'text-danger' : 'text-success' ?>">Rs. <?= number_format((float) $record['difference_amount'], 2) ?></strong></div><div class="col-md-4"><span class="muted-label">Closed at</span><strong class="d-block fs-5"><?= e((string) $record['closed_at']) ?></strong></div></div><?php endif; ?>
    </div>
    <?php if ($record['status'] === 'closed'): ?><div class="admin-panel mt-4"><div class="panel-heading"><div><h2>Cash Handover</h2><p class="empty-note">Hand over the counted cash to the administrator for acceptance.</p></div><span class="status-badge <?= ($record['handover_status'] ?? 'not_submitted') === 'accepted' ? 'status-success' : (($record['handover_status'] ?? 'not_submitted') === 'pending' ? 'status-warning' : 'status-pending') ?>"><?= e(ucfirst(str_replace('_', ' ', $record['handover_status'] ?? 'not_submitted'))) ?></span></div><?php if (($record['handover_status'] ?? 'not_submitted') === 'not_submitted'): ?><form method="post" class="row g-3 align-items-end"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="register_action" value="handover"><input type="hidden" name="register_date" value="<?= e($date) ?>"><div class="col-md-4"><label class="form-label">Cash handed over (Rs.)</label><input class="form-control" type="number" name="handover_amount" min="0" step="0.01" value="<?= e((string) ($record['actual_closing_amount'] ?? $totals['expected'])) ?>" required></div><div class="col-md-5"><label class="form-label">Note</label><input class="form-control" type="text" name="notes" placeholder="Optional handover note"></div><div class="col-md-3"><button class="btn btn-danger w-100" type="submit">Hand Over Cash</button></div></form><?php elseif (($record['handover_status'] ?? '') === 'accepted'): ?><p class="mb-0 text-success">Admin accepted Rs. <?= number_format((float) $record['accepted_amount'], 2) ?>.</p><?php else: ?><p class="mb-0">Cash handover is waiting for admin acceptance.</p><?php endif; ?></div><?php endif; ?>
    <div class="admin-panel mt-4"><div class="panel-heading"><div><h2>Cash Movement</h2><p class="empty-note"><?= count($transactions) ?> transaction(s) recorded for <?= e(date('d M Y', strtotime($date))) ?>.</p></div></div><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Time</th><th>Type</th><th>Description</th><th>Reference</th><th class="text-end">Amount</th></tr></thead><tbody><?php if (!$transactions): ?><tr><td colspan="5" class="empty-table">No cash movement recorded yet.</td></tr><?php else: foreach ($transactions as $transaction): ?><tr><td><?= e(date('H:i', strtotime((string) $transaction['happened_at']))) ?></td><td><?= e($transaction['type']) ?></td><td><?= e($transaction['description']) ?></td><td><?= e((string) ($transaction['reference'] ?? '-')) ?></td><td class="text-end <?= $transaction['direction'] === 'in' ? 'text-success' : 'text-danger' ?>"><?= $transaction['direction'] === 'in' ? '+' : '-' ?> Rs. <?= number_format((float) $transaction['amount'], 2) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
    <div class="admin-panel mt-4"><div class="panel-heading"><div><h2>My Handover History</h2><p class="empty-note">Review your previous cash handovers and their acceptance status.</p></div><span class="muted-label"><?= count($historyRows) ?> record(s)</span></div><form method="get" class="filter-bar"><input type="hidden" name="page" value="admin"><input type="hidden" name="section" value="cashier-register"><input type="hidden" name="register_date" value="<?= e($date) ?>"><select class="form-select" name="history_status"><option value="">All statuses</option><option value="pending" <?= $historyStatus === 'pending' ? 'selected' : '' ?>>Pending</option><option value="accepted" <?= $historyStatus === 'accepted' ? 'selected' : '' ?>>Accepted</option><option value="rejected" <?= $historyStatus === 'rejected' ? 'selected' : '' ?>>Rejected</option></select><input class="form-control" type="date" name="history_from" value="<?= e($historyFrom) ?>"><input class="form-control" type="date" name="history_to" value="<?= e($historyTo) ?>"><button class="btn btn-primary" type="submit">Filter</button><a class="btn btn-light" href="index.php?page=admin&amp;section=cashier-register&amp;register_date=<?= e(rawurlencode($date)) ?>">Reset</a></form><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Date</th><th>Expected</th><th>Handed Over</th><th>Received</th><th>Balance</th><th>Status</th><th>Accepted At</th></tr></thead><tbody><?php if (!$historyRows): ?><tr><td colspan="7" class="empty-table">No handover history found.</td></tr><?php else: foreach ($historyRows as $historyRow): ?><tr><td><?= e($historyRow['register_date']) ?></td><td>Rs. <?= number_format((float) $historyRow['expected_closing_amount'], 2) ?></td><td>Rs. <?= number_format((float) ($historyRow['handover_amount'] ?? 0), 2) ?></td><td><?= $historyRow['accepted_amount'] === null ? '-' : 'Rs. '.number_format((float) $historyRow['accepted_amount'], 2) ?></td><td class="<?= $historyRow['balance_amount'] > 0 ? 'text-danger' : 'text-success' ?>"><?= $historyRow['balance_amount'] > 0 ? 'Due Rs. '.number_format($historyRow['balance_amount'], 2) : 'Balanced' ?></td><td><?= e(ucfirst($historyRow['handover_status'])) ?></td><td><?= e((string) ($historyRow['accepted_at'] ?? '-')) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
<?php endif; ?>
<?php require __DIR__ . '/../includes/footer.php'; ?>
