<?php $isPaid = ($salaryReceipt['status'] ?? '') === 'paid'; $receiptSettings = receipt_settings(); ?>
<div class="customer-modal-backdrop" role="presentation">
    <section class="customer-modal salary-receipt-modal" role="dialog" aria-modal="true" aria-labelledby="salary-receipt-title">
        <div class="customer-modal-header"><div><span class="modal-eyebrow"><?= $isPaid ? 'Payment receipt' : 'Salary calculation' ?></span><h2 id="salary-receipt-title"><?= $isPaid ? 'Salary Payment Receipt' : 'Salary Calculation Receipt' ?></h2><span class="modal-code"><?= e($salaryReceipt['receipt_no'] ?: 'PENDING') ?></span></div><a class="customer-modal-close" href="index.php?page=admin&amp;section=employees-salary" aria-label="Close">&times;</a></div>
        <div class="customer-modal-body">
            <div class="salary-receipt-card salary-print-card">
                <header class="salary-print-brand"><strong><?= e($receiptSettings['garage_name']) ?></strong><?php if ($receiptSettings['tagline']): ?><span><?= e($receiptSettings['tagline']) ?></span><?php endif; ?><?php if ($receiptSettings['address']): ?><span><?= e($receiptSettings['address']) ?></span><?php endif; ?><?php if ($receiptSettings['contact_number']): ?><span><?= e($receiptSettings['contact_number']) ?></span><?php endif; ?><?php if ($receiptSettings['email']): ?><span><?= e($receiptSettings['email']) ?></span><?php endif; ?></header>
                <?php if ($receiptSettings['receipt_header']): ?><div class="salary-print-note"><?= nl2br(e($receiptSettings['receipt_header'])) ?></div><?php endif; ?>
                <div class="salary-print-title"><h3><?= $isPaid ? 'PAYMENT RECEIPT' : 'SALARY CALCULATION' ?></h3><span><?= $isPaid ? 'Thank you for your service' : 'Pending payment' ?></span></div>
                <div class="salary-print-meta"><div><span>Receipt No</span><strong><?= e($salaryReceipt['receipt_no'] ?: 'PENDING') ?></strong></div><div><span>Salary Month</span><strong><?= e(date('F Y', strtotime($salaryReceipt['salary_month']))) ?></strong></div><div><span>Status</span><strong><?= e(strtoupper($salaryReceipt['status'])) ?></strong></div><div><span><?= $isPaid ? 'Paid Date & Time' : 'Calculated Date & Time' ?></span><strong><?= e($isPaid ? ($salaryReceipt['paid_at'] ?: '-') : date('Y-m-d H:i:s')) ?></strong></div></div>
                <div class="salary-print-section"><h4>Employee Details</h4><div class="salary-print-line"><span>Employee</span><strong><?= e($salaryReceipt['employee_name']) ?></strong></div><div class="salary-print-line"><span>Employee Code</span><strong><?= e($salaryReceipt['employee_code']) ?></strong></div></div>
            <div class="salary-print-section"><h4>Salary Details</h4><div class="salary-print-line"><span>Basic Salary</span><strong><?= number_format((float)$salaryReceipt['basic_salary'], 2) ?></strong></div><div class="salary-print-line"><span>Allowances</span><strong><?= number_format((float)$salaryReceipt['allowances'], 2) ?></strong></div><div class="salary-print-line"><span>No-pay Leave Days</span><strong><?= number_format((float)($salaryReceipt['unpaid_leave_days'] ?? 0), 2) ?></strong></div><div class="salary-print-line"><span>No-pay Leave Deduction</span><strong><?= number_format((float)($salaryReceipt['attendance_deduction'] ?? 0), 2) ?></strong></div><div class="salary-print-line"><span>Advance Deduction</span><strong><?= number_format((float)($salaryReceipt['advance_deduction'] ?? 0), 2) ?></strong></div><div class="salary-print-line"><span>Loan Deduction</span><strong><?= number_format((float)($salaryReceipt['loan_deduction'] ?? 0), 2) ?></strong></div><div class="salary-print-line"><span>Other Deductions</span><strong><?= number_format(max(0, (float)$salaryReceipt['deductions'] - (float)($salaryReceipt['attendance_deduction'] ?? 0) - (float)($salaryReceipt['advance_deduction'] ?? 0) - (float)($salaryReceipt['loan_deduction'] ?? 0)), 2) ?></strong></div><div class="salary-print-total"><span>Total Deductions</span><strong><?= number_format((float)$salaryReceipt['deductions'], 2) ?></strong></div><div class="salary-print-grand-total"><span><?= $isPaid ? 'Amount Paid' : 'Amount Payable' ?></span><strong><?= number_format((float)$salaryReceipt['net_salary'], 2) ?></strong></div></div>
                <?php if ($receiptSettings['receipt_footer']): ?><footer class="salary-print-footer"><?= nl2br(e($receiptSettings['receipt_footer'])) ?></footer><?php endif; ?><div class="salary-print-signature">Authorized by Deshappriya Motors</div>
            </div>
        </div>
        <div class="customer-modal-footer"><button class="btn btn-primary" type="button" onclick="window.print()">Print 88mm Receipt</button><a class="btn btn-light" href="index.php?page=admin&amp;section=employees-salary">Close</a></div>
    </section>
</div>
<?php if (($_GET['receipt_mode'] ?? '') === 'download'): ?><script>window.addEventListener('load', () => window.print());</script><?php endif; ?>
