<?php $labels=['draft'=>'Draft','pending'=>'Pending','paid'=>'Paid','partial'=>'Partial','due'=>'Due','cancelled'=>'Cancelled']; ?>
<div class="expense-list-background" inert aria-hidden="true">
<?php
(static function (): void {
    $user = current_user();
    $filters = ['search' => '', 'status' => '', 'from' => '', 'to' => '',
        'created_by' => ($user['role'] ?? '') === 'cashier' ? (int) ($user['id'] ?? 0) : 0];
    $rows = expense_rows($filters);
    $summary = expense_summary();
    require __DIR__ . '/expenses.php';
})();
?>
</div>
<div class="customer-modal-backdrop expense-view-backdrop"><section class="customer-modal expense-view-modal" role="dialog" aria-modal="true" aria-labelledby="expense-details-title"><div class="customer-modal-header"><div><span class="modal-eyebrow"><?= e($record['expense_no']) ?></span><h2 id="expense-details-title">Expense Details</h2><span class="modal-code"><?= e($record['expense_date']) ?></span></div><a class="customer-modal-close" href="index.php?page=admin&amp;section=expenses">&times;</a></div><div class="customer-modal-body"><span class="expense-status expense-status-<?= e($record['status']) ?>"><?= e($labels[$record['status']]??$record['status']) ?></span><div class="modal-detail-grid"><div><span>Category</span><strong><?= e($record['category']) ?></strong></div><div><span>Supplier / Vendor</span><strong><?= e($record['supplier_name']?:'-') ?></strong></div><div><span>Description</span><strong><?= e($record['description']) ?></strong></div><div><span>Payment</span><strong><?= e(ucfirst($record['payment_method'])) ?></strong></div></div><div class="expense-view-items"><h3>Expense Items</h3><table class="table admin-table"><thead><tr><th>Item</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead><tbody><?php foreach($record['items'] as $item): ?><tr><td><?= e($item['item_name']) ?></td><td><?= number_format((float)$item['quantity'],2) ?></td><td><?= number_format((float)$item['unit_price'],2) ?></td><td><?= number_format((float)$item['amount'],2) ?></td></tr><?php endforeach; ?></tbody></table><div class="expense-view-total"><span>Subtotal</span><strong>Rs. <?= number_format((float)$record['subtotal'],2) ?></strong><span>Discount</span><strong>Rs. <?= number_format((float)$record['discount'],2) ?></strong><span>Tax</span><strong>Rs. <?= number_format((float)$record['tax_amount'],2) ?></strong><b>Total</b><b>Rs. <?= number_format((float)$record['total_amount'],2) ?></b><span>Paid</span><strong>Rs. <?= number_format((float)$record['paid_amount'],2) ?></strong><span>Balance</span><strong>Rs. <?= number_format((float)$record['balance_amount'],2) ?></strong></div></div></div><div class="customer-modal-footer"><a class="btn btn-light" href="index.php?page=admin&amp;section=expenses">Close</a><?php if ((current_user()['role'] ?? '') === 'administrator'): ?><a class="btn btn-danger" href="index.php?page=admin&amp;section=expenses-edit&amp;id=<?= (int)$record['id'] ?>">Edit Expense</a><?php endif; ?></div></section></div>
<section class="admin-panel audit-panel"><div class="panel-heading"><h2>Record Audit</h2></div><div class="audit-record"><strong><?= e($record['expense_no']) ?></strong><span>Added by: <?= e($record['created_by_name'] ?: 'Unknown user') ?></span></div></section>
