<?php
$status = (string)($job['status'] ?? 'pending');
$statusLabel = strtoupper($status);
$backSection = $status === 'completed' ? 'jobcards-completed' : 'jobcards-pending';
?>
<div class="friendly-job-view"><div class="page-heading jobcard-heading compact-jobcard-page">
    <div>
        <div class="edit-job-kicker"><span class="edit-job-pulse"></span> Job card details</div>
        <h1>Job Card <span><?= e($job['job_card_no']) ?></span></h1>
        <nav class="job-breadcrumb"><a href="index.php?page=admin">Dashboard</a><span>›</span><a href="index.php?page=admin&amp;section=<?= e($backSection) ?>">Job Cards</a><span>›</span><strong>View Details</strong></nav>
    </div>
    <div class="jobcard-top-actions">
        <a class="btn btn-light" href="index.php?page=admin&amp;section=<?= e($backSection) ?>">Back to Job Cards</a>
        <?php if (in_array($status, ['pending', 'ongoing'], true)): ?><a class="btn btn-primary" href="index.php?page=admin&amp;section=jobcards-edit&amp;id=<?= (int)$job['id'] ?>">Edit Job Card</a><?php endif; ?>
    </div>
</div>
<?php if ($status === 'pending'): ?><div class="view-next-step"><strong>This job is waiting to start.</strong><span>Check the work below, then choose Start Job to assign a bay and mechanic.</span></div><?php endif; ?><section class="jobcard-layout view-jobcard-layout">
    <main>
        <section class="admin-panel jobcard-section view-identity-card"><div class="edit-identity-icon">JC</div><div><span class="edit-section-label">Job card</span><strong><?= e($job['job_card_no']) ?></strong><small>Created <?= e(date('d M Y, h:i A', strtotime($job['created_at']))) ?></small></div><div class="edit-identity-divider"></div><div><span class="edit-section-label">Customer</span><strong><?= e($job['customer_name']) ?></strong><small><?= e($job['contact_number'] ?: 'No contact number') ?></small></div><div class="edit-identity-divider"></div><div><span class="edit-section-label">Vehicle</span><strong><?= e($job['vehicle_number'] ?: 'No vehicle') ?></strong><small><?= e(trim(($job['make'] ?: '') . ' ' . ($job['model'] ?: ''))) ?></small></div><span class="edit-status-pill"><?= e($statusLabel) ?></span></section>
        <details class="admin-panel jobcard-section view-extra-details"><summary>Customer &amp; vehicle details <span>Contact information and vehicle details</span></summary><div class="view-info-grid"><div><span>Customer</span><strong><?= e($job['customer_name']) ?></strong><small><?= e($job['contact_number'] ?: '-') ?><?= $job['email'] ? ' · ' . e($job['email']) : '' ?></small></div><div><span>Vehicle</span><strong><?= e($job['vehicle_number'] ?: '-') ?></strong><small><?= e(trim(($job['vehicle_type'] ?: '') . ' · ' . ($job['make'] ?: '') . ' ' . ($job['model'] ?: ''))) ?></small></div></div></details>
        <section class="admin-panel jobcard-section"><div class="edit-section-heading"><span class="edit-section-number">1</span><div><h2>What needs to be done?</h2><p>Read the customer complaint and the work requested.</p></div></div><div class="view-copy-grid"><div><span>Customer complaint</span><p><?= nl2br(e($job['complaint'] ?: '-')) ?></p></div><div><span>Requested services / work</span><p><?= nl2br(e($job['requested_work'] ?: '-')) ?></p></div></div></section>
        <section class="admin-panel jobcard-section"><div class="edit-section-heading"><span class="edit-section-number">2</span><div><h2>Services &amp; charges</h2><p>Items and prices already added to this job.</p></div></div><?php if (!empty($job['items'])): ?><div class="table-responsive"><table class="table admin-table view-items-table"><thead><tr><th>Item</th><th>Type</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody><?php foreach ($job['items'] as $item): ?><tr><td><strong><?= e($item['item_name']) ?><?php if (item_price_reduction($item) > 0): ?><small class="d-block text-muted">List price: Rs. <?= number_format((float)$item['list_unit_price'],2) ?> &middot; Part price reduction: Rs. <?= number_format(item_price_reduction($item),2) ?> (included)</small><?php endif; ?></strong><small><?= e($item['item_code'] ?: '-') ?></small></td><td><?= e(ucfirst($item['item_type'])) ?></td><td><?= e((string)$item['quantity']) ?></td><td>Rs. <?= number_format((float)$item['unit_price'], 2) ?></td><td><strong>Rs. <?= number_format((float)$item['amount'], 2) ?></strong></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><div class="edit-empty-items">No services or items have been added to this job card.</div><?php endif; ?><div class="view-total-row"><span>Subtotal</span><strong>Rs. <?= number_format((float)$job['subtotal'], 2) ?></strong><span>Service charge</span><strong>Rs. <?= number_format((float)$job['service_charge'], 2) ?></strong><span>Total</span><strong>Rs. <?= number_format((float)$job['total_amount'], 2) ?></strong></div></section>
    </main>
    <aside class="admin-panel jobcard-preview view-summary-panel"><h2>Job at a glance</h2><div class="preview-row"><span>Status</span><strong><?= e($statusLabel) ?></strong></div><div class="preview-row"><span>Working bay</span><strong><?= e($job['bay_name'] ?: 'Not assigned') ?></strong></div><div class="preview-row"><span>Mechanic</span><strong><?= e($job['mechanic_name'] ?: 'Not assigned') ?></strong></div><div class="preview-row"><span>Expected delivery</span><strong><?= e($job['expected_delivery_date'] ?: '-') ?></strong></div><div class="preview-row"><span>Priority</span><strong><?= e(ucfirst($job['priority'])) ?></strong></div><div class="ongoing-amount"><span>Job total</span><strong>Rs. <?= number_format((float)$job['total_amount'], 2) ?></strong><small>Amount due: Rs. <?= number_format((float)$job['balance_amount'], 2) ?></small></div><?php if (!empty($job['notes'])): ?><div class="preview-note"><strong>Internal notes</strong><p><?= nl2br(e($job['notes'])) ?></p></div><?php endif; ?><?php if (in_array($status, ['pending', 'ongoing'], true)): ?><div class="view-summary-actions"><a class="btn btn-primary w-100" href="index.php?page=admin&amp;section=jobcards-edit&amp;id=<?= (int)$job['id'] ?>">Edit Job Card</a><?php if ($status === 'pending'): ?><a class="btn btn-light w-100" href="index.php?page=admin&amp;section=jobcards-start&amp;id=<?= (int)$job['id'] ?>">Start Job</a><?php endif; ?></div><?php endif; ?></aside>
</section>

</div>
