<div class="page-heading"><div><h1>Customer Payments</h1><p>Find an invoice and click Pay to collect its outstanding balance.</p></div></div>
<section class="admin-panel mb-3"><form method="get" class="row g-3 align-items-end">
<input type="hidden" name="page" value="admin"><input type="hidden" name="section" value="payments">
<div class="col-md-4"><label class="form-label" for="payment-search">Search</label><input class="form-control" id="payment-search" name="search" value="<?= e($search) ?>" placeholder="Customer, phone, customer code or invoice..."></div>
<div class="col-md-3"><label class="form-label" for="payment-customer">Customer</label><select class="form-select" id="payment-customer" name="customer_id"><option value="0">All customers</option><?php foreach ($customers as $customer): ?><option value="<?= (int)$customer['id'] ?>" <?= $customerId === (int)$customer['id'] ? 'selected' : '' ?>><?= e($customer['name'].' - '.$customer['customer_code']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label class="form-label" for="payment-status">Payment Status</label><select class="form-select" id="payment-status" name="status"><?php foreach (['outstanding'=>'Due & Partial','all'=>'All Invoices','due'=>'Due (Unpaid)','partial'=>'Partial Payment','paid'=>'Paid'] as $value=>$label): ?><option value="<?= e($value) ?>" <?= $status === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div>
<div class="col-md-2 d-flex gap-2"><button class="btn btn-primary">Search</button><a class="btn btn-light" href="index.php?page=admin&amp;section=payments">Reset</a></div>
</form></section>
<section class="admin-panel mb-3"><div class="panel-heading"><h2>Payments List <span class="service-count-badge"><?= $total ?></span></h2><strong>Filtered Due: Rs. <?= number_format($totalDue, 2) ?></strong></div>
<div class="table-responsive"><table class="table admin-table"><thead><tr><th>#</th><th>Customer</th><th>Invoice</th><th>Date</th><th>Total (Rs.)</th><th>Paid (Rs.)</th><th>Due (Rs.)</th><th>Status</th><th>Action</th></tr></thead><tbody>
<?php if (!$rows): ?><tr><td colspan="9" class="empty-table">No invoices match your filters.</td></tr><?php endif; ?>
<?php foreach ($rows as $index=>$invoice): ?><tr><td><?= $offset+$index+1 ?></td><td><strong><?= e($invoice['customer_name'] ?: 'Walk-in Customer') ?></strong><small class="d-block"><?= e($invoice['contact_number'] ?: '') ?></small></td><td><?= e($invoice['invoice_no']) ?></td><td><?= e($invoice['invoice_date']) ?></td><td><?= number_format((float)$invoice['total_amount'],2) ?></td><td><?= number_format((float)$invoice['paid_amount'],2) ?></td><td><?= number_format((float)$invoice['balance_amount'],2) ?></td><td><span class="badge <?= $invoice['payment_status']==='paid'?'bg-success':($invoice['payment_status']==='partial'?'bg-warning text-dark':'bg-danger') ?>"><?= e(ucfirst($invoice['payment_status'])) ?></span></td><td><div class="d-flex gap-2">
<?php if ((float)$invoice['balance_amount']>0.009 && in_array($invoice['payment_status'],['due','partial'],true)): ?><button type="button" class="btn btn-primary btn-sm" data-collect-payment data-invoice-id="<?= (int)$invoice['id'] ?>" data-invoice-no="<?= e($invoice['invoice_no']) ?>" data-customer="<?= e($invoice['customer_name'] ?: 'Walk-in Customer') ?>" data-due="<?= e($invoice['balance_amount']) ?>">Pay</button><?php endif; ?><a class="btn btn-light btn-sm" href="index.php?page=admin&amp;section=invoices-view&amp;id=<?= (int)$invoice['id'] ?>">View</a></div></td></tr><?php endforeach; ?>
</tbody></table></div><div class="customer-table-footer"><span>Showing <?= $total?$offset+1:0 ?> to <?= $offset+count($rows) ?> of <?= $total ?> invoices</span>
<?php if ($pages>1): ?><nav aria-label="Payments pagination"><ul class="pagination pagination-sm mb-0"><?php for($number=1;$number<=$pages;$number++): ?><li class="page-item <?= $number===$currentPage?'active':'' ?>"><a class="page-link" <?= $number===$currentPage?'aria-current="page"':'' ?> href="<?= e($paginationUrl.'&p='.$number) ?>"><?= $number ?></a></li><?php endfor; ?></ul></nav><?php endif; ?></div></section>
<dialog class="vehicle-update-confirm" id="collect-payment-dialog" aria-labelledby="collect-payment-title">
<h2 id="collect-payment-title">Record Payment</h2><p data-payment-description></p><p>Outstanding: <strong data-payment-due></strong></p>
<form method="post" data-collect-payment-form><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>">
<label class="form-label" for="collect-amount">Amount Received (Rs.)</label><input class="form-control mb-3" id="collect-amount" type="number" name="amount_received" min="0.01" step="0.01" required><small class="d-block mb-3">Pay part of the balance or the full amount.</small>
<label class="form-label" for="collect-method">Payment Method</label><select class="form-select mb-3" id="collect-method" name="payment_method"><option value="cash">Cash</option><option value="card">Card</option><option value="bank">Bank Transfer</option><option value="cheque">Cheque</option><option value="other">Other</option></select>
<label class="form-label" for="collect-reference">Reference (Optional)</label><input class="form-control mb-3" id="collect-reference" name="payment_reference" maxlength="100">
<div class="d-flex gap-2 justify-content-end"><button class="btn btn-light" type="button" data-close-payment>Cancel</button><button class="btn btn-primary" type="submit">Save Payment &amp; Receipt</button></div></form></dialog>
<details class="admin-panel"><summary>Recent Payment Receipts</summary><p class="mt-3">Latest 20 payments for the selected customer.</p><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Receipt</th><th>Customer</th><th>Invoice</th><th>Date</th><th>Applied (Rs.)</th><th>Action</th></tr></thead><tbody>
<?php if (!$history): ?><tr><td colspan="6">No payments recorded.</td></tr><?php endif; ?>
<?php foreach($history as $payment): ?><tr><td><?= e($payment['payment_no']) ?></td><td><?= e($payment['customer_name'] ?: 'Walk-in Customer') ?></td><td><?= e($payment['invoice_no']) ?></td><td><?= e($payment['payment_date']) ?></td><td><?= number_format((float)$payment['amount_applied'],2) ?></td><td><a class="btn btn-light btn-sm" href="index.php?page=admin&amp;section=invoices-receipt&amp;id=<?= (int)$payment['id'] ?>">Receipt</a></td></tr><?php endforeach; ?></tbody></table></div></details>
<script src="assets/js/customer-payments.js?v=<?= (int)filemtime(__DIR__.'/../assets/js/customer-payments.js') ?>"></script>