<div class="service-list-background" inert aria-hidden="true">
<?php
(static function (): void {
    $filters = ['search' => '', 'category_id' => 0, 'status' => '', 'page' => 1, 'per_page' => 10];
    [$rows, $total] = service_rows($filters);
    $summary = service_summary();
    $categories = service_categories();
    $pages = max(1, (int) ceil($total / $filters['per_page']));
    require __DIR__ . '/services.php';
})();
?>
</div>
<div class="service-drawer-backdrop service-form-centered"><section class="service-drawer" role="dialog" aria-modal="true" aria-labelledby="service-form-title"><div class="service-drawer-header"><div><h2 id="service-form-title"><?= e($title) ?></h2><small><?= $editing?'Update service details':'Create a new service' ?></small></div><a href="index.php?page=admin&amp;section=services">&times;</a></div><form method="post" action="index.php?page=admin&amp;section=<?= e($section) ?>&amp;id=<?= (int)$id ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><?php if($errors): ?><div class="alert alert-danger"><?php foreach($errors as $error): ?><div><?= e($error) ?></div><?php endforeach; ?></div><?php endif; ?><label class="form-label">Service Code<input class="form-control" value="<?= e($editing?$service['service_code']:'Auto generated') ?>" readonly><small>Auto generated</small></label><label class="form-label">Service Name *<input class="form-control" name="service_name" value="<?= e($input['service_name']) ?>" required></label><label class="form-label">Category *<span class="service-add-category"><a href="index.php?page=admin&amp;section=services">+ Add Category</a></span><select class="form-select" name="category_id" required><option value="0">Select category</option><?php foreach($categories as $category): ?><option value="<?= (int)$category['id'] ?>" <?= $input['category_id']==(int)$category['id']?'selected':'' ?>><?= e($category['category_name']) ?></option><?php endforeach; ?></select></label><label class="form-label">Description<textarea class="form-control" name="description" rows="3"><?= e($input['description']) ?></textarea></label><div class="row g-3"><div class="col-6"><label class="form-label">Price (Rs.) *<input class="form-control" type="number" min="0" step="0.01" name="price" value="<?= e($input['price']) ?>" required></label></div><div class="col-6"><label class="form-label">Duration (Minutes)<input class="form-control" type="number" min="0" name="duration_minutes" value="<?= e($input['duration']) ?>"></label></div></div><label class="form-label">Status<select class="form-select" name="status"><option value="active" <?= $input['status']==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= $input['status']==='inactive'?'selected':'' ?>>Inactive</select></label><div class="service-drawer-actions"><a class="btn btn-light" href="index.php?page=admin&amp;section=services">Cancel</a><button class="btn btn-danger">Save Service</button></div></form></section></div>
