<div class="stock-list-background" inert aria-hidden="true">
<?php
(static function (): void {
    $section = 'stock';
    $title = 'Stock / Parts';
    $filters = ['search' => '', 'category' => '', 'brand' => '', 'status' => ''];
    $rows = stock_items($filters);
    $summary = stock_summary();
    $categories = stock_categories();
    $brands = stock_brands();
    require __DIR__ . '/stock.php';
})();
?>
</div>
<?php $stockStatus=(float)$item['stock_qty']<=0?'out':((float)$item['stock_qty']<=(float)$item['reorder_level']?'low':'in');$statusText=$stockStatus==='out'?'Out of Stock':($stockStatus==='low'?'Low Stock':'In Stock'); ?>
<div class="customer-modal-backdrop stock-view-backdrop" role="presentation"><section class="customer-modal stock-detail-modal" role="dialog" aria-modal="true"><div class="customer-modal-header"><div><span class="modal-eyebrow"><?= e($item['part_code']) ?></span><h2><?= e($item['part_name']) ?></h2><span class="modal-code">Stock item details</span></div><a class="customer-modal-close" href="index.php?page=admin&amp;section=stock">&times;</a></div><div class="customer-modal-body"><div class="modal-status-row"><span class="stock-status stock-status-<?= $stockStatus ?>"><?= e($statusText) ?></span></div><div class="modal-detail-grid"><div><span>Category</span><strong><?= e($item['category']?:'-') ?></strong></div><div><span>Brand</span><strong><?= e($item['brand']?:'-') ?></strong></div><div><span>Unit</span><strong><?= e($item['unit']) ?></strong></div><div><span>Supplier</span><strong><?= e($item['supplier_name']?:'-') ?></strong></div><div><span>Average Cost</span><strong>Rs. <?= number_format((float)$item['average_cost'],2) ?></strong></div><div><span>Current Selling Price</span><strong>Rs. <?= number_format((float)$item['selling_price'],2) ?></strong></div><div><span>Current Stock</span><strong><?= number_format((float)$item['stock_qty'],2) ?></strong></div><div><span>Low Stock Level</span><strong><?= number_format((float)$item['reorder_level'],2) ?></strong></div><div class="modal-detail-wide"><span>Notes</span><strong><?= nl2br(e($item['notes']?:'-')) ?></strong></div></div>
<div class="stock-history-section"><h3>Purchase / Batch History</h3><div class="table-responsive"><table class="table admin-table stock-history-table"><thead><tr><th>Batch No.</th><th>Purchase Date</th><th>Supplier</th><th>Received</th><th>Remaining</th><th>Buying Price</th><th>Invoice</th><th>Status</th></tr></thead><tbody><?php if(!$batches): ?><tr><td colspan="8" class="empty-table">No batch history yet.</td></tr><?php else: foreach($batches as $batch): $batchStatus=(float)$batch['quantity_remaining']<=0?'Exhausted':((float)$batch['quantity_remaining']<(float)$batch['quantity_received']?'Partially Used':'Available'); ?><tr><td><?= e($batch['batch_reference']?:'-') ?></td><td><?= e($batch['purchase_date']) ?></td><td><?= e($batch['supplier_name']?:'-') ?></td><td><?= number_format((float)$batch['quantity_received'],2) ?></td><td><?= number_format((float)$batch['quantity_remaining'],2) ?></td><td>Rs. <?= number_format((float)$batch['buying_price'],2) ?></td><td><?= e($batch['invoice_no']?:'-') ?></td><td><?= e($batchStatus) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
<div class="stock-history-section"><h3>Stock Movement History</h3><div class="table-responsive"><table class="table admin-table stock-history-table"><thead><tr><th>Date</th><th>Movement</th><th>Reference</th><th>Qty In</th><th>Qty Out</th><th>Before</th><th>After</th><th>Unit Cost</th><th>User</th></tr></thead><tbody><?php if(!$movements): ?><tr><td colspan="9" class="empty-table">No movement history yet.</td></tr><?php else: foreach($movements as $movement): $incoming=in_array($movement['movement_type'],['opening_stock','restock','adjustment_in','return'],true); ?><tr><td><?= e($movement['created_at']) ?></td><td><?= e(movement_label($movement['movement_type'])) ?></td><td><?= e(($movement['reference_type']?:'-').' '.($movement['reference_id']?:'')) ?></td><td><?= $incoming?number_format((float)$movement['quantity'],2):'-' ?></td><td><?= $incoming?'-':number_format((float)$movement['quantity'],2) ?></td><td><?= number_format((float)$movement['quantity_before'],2) ?></td><td><?= number_format((float)$movement['quantity_after'],2) ?></td><td>Rs. <?= number_format((float)$movement['unit_cost'],2) ?></td><td><?= e($movement['user_name']?:'-') ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div></div><div class="customer-modal-footer"><a class="btn btn-light" href="index.php?page=admin&amp;section=stock">Close</a><a class="btn btn-light" href="index.php?page=admin&amp;section=stock-restock&amp;stock_item_id=<?= (int)$item['id'] ?>">Restock Item</a><?php if ((current_user()['role'] ?? '') !== 'cashier'): ?><a class="btn btn-danger" href="index.php?page=admin&amp;section=stock-edit&amp;id=<?= (int)$item['id'] ?>">Edit Stock</a><?php endif; ?></div></section></div>
