<?php
$adminMenu = [
    'Dashboard' => ['dashboard'], 'Customers' => ['customers', 'customers-add'], 'Vehicles' => ['vehicles', 'vehicles-add'],
    'Job Cards' => ['jobcards-new', 'jobcards-pending', 'jobcards-ongoing', 'jobcards-completed'], 'Appointments' => ['appointments'], 'Estimates' => ['estimates'], 'Invoices' => ['invoices', 'invoices-quick'], 'Payments' => ['payments'], 'Expenses' => ['expenses', 'expenses-categories'],
    'Stock / Parts' => ['stock', 'stock-add', 'stock-purchases', 'stock-low'], 'Services' => ['services'], 'Suppliers' => ['suppliers', 'suppliers-add'], 'Employees' => ['employees', 'employees-add', 'employees-salary', 'employees-advances', 'employees-loans', 'employees-attendance'], 'Other Income' => ['other-income'], 'Cashier Handovers' => ['cashier-handovers'], 'Advance Requests' => ['cashier-advance-requests'], 'Bay Management' => ['bays'],
    'Reports' => ['reports-sales', 'reports-job-cards', 'reports-invoices', 'reports-expenses', 'reports-stock', 'reports-customers', 'reports-vehicles', 'reports-mechanics', 'reports-bays', 'reports-payments', 'reports-profit-loss', 'reports-today-profit'], 'User Management' => ['users-cashiers'], 'Settings' => ['settings'],
];
$labels = ['dashboard'=>'Dashboard','customers'=>'All Customers','customers-add'=>'Add Customer','vehicles'=>'All Vehicles','vehicles-add'=>'Add Vehicle','jobcards-new'=>'New Job Card','jobcards-pending'=>'Pending Job Cards','jobcards-ongoing'=>'Ongoing Job Cards','jobcards-completed'=>'Completed Job Cards','appointments'=>'Appointments','estimates'=>'Estimates','invoices'=>'All Invoices','invoices-quick'=>'Quick Invoice','payments'=>'Payments','expenses'=>'Expense List','expenses-categories'=>'Expense Categories','stock'=>'Stock List','stock-add'=>'Add Stock','stock-purchases'=>'Stock Purchases','stock-low'=>'Low Stock','services'=>'Services','suppliers'=>'All Suppliers','suppliers-add'=>'Add Supplier','employees'=>'Employee List','employees-add'=>'Add Employee','employees-salary'=>'Salary Management','employees-advances'=>'Staff Advances','employees-loans'=>'Staff Loans','employees-attendance'=>'Attendance','other-income'=>'Other Income','cashier-handovers'=>'Cashier Handovers','cashier-advance-requests'=>'Advance Requests','bays'=>'Bay Management','reports-sales'=>'Sales Reports','reports-job-cards'=>'Job Card Reports','reports-invoices'=>'Invoice Reports','reports-expenses'=>'Expense Reports','reports-stock'=>'Stock Reports','reports-customers'=>'Customer Reports','reports-vehicles'=>'Vehicle Reports','reports-mechanics'=>'Mechanic Reports','reports-bays'=>'Bay Reports','reports-payments'=>'Payment Reports','reports-profit-loss'=>'Profit & Loss','reports-today-profit'=>'Today Profit','users-cashiers'=>'User Management','settings'=>'Settings'];
?><aside class="sidebar admin-sidebar" data-sidebar>
    <div class="brand"><div class="brand-mark">DM</div><div><strong>DESHAPRIYA<br>MOTORS</strong><small>Garage management system</small></div></div>
    <nav class="sidebar-nav"><span class="nav-label">Main menu</span><label class="sidebar-search"><span>Search menu</span><input type="search" placeholder="Find a page..." autocomplete="off" data-sidebar-search></label><div data-sidebar-items><?php foreach ($adminMenu as $group => $items): ?><?php if (count($items) === 1): ?><a class="nav-link <?= $section === $items[0] || ($items[0] === 'dashboard' && ($section ?? '') === '') ? 'active' : '' ?>" data-sidebar-item href="index.php?page=admin&amp;section=<?= e($items[0]) ?>"><span><?= $section === $items[0] ? '&#9679;' : '&#9632;' ?></span><?= e($group) ?></a><?php else: ?><details class="nav-group" <?= in_array($section, $items, true) ? 'open' : '' ?> data-sidebar-group><summary><span class="nav-group-icon">&#9632;</span><?= e($group) ?></summary><?php foreach ($items as $item): ?><a class="nav-sublink <?= $section === $item ? 'active' : '' ?>" data-sidebar-item href="index.php?page=admin&amp;section=<?= e($item) ?>"><?= e($labels[$item] ?? $item) ?></a><?php endforeach; ?></details><?php endif; ?><?php endforeach; ?></div><p class="sidebar-no-results" data-sidebar-no-results hidden>No matching pages found.</p></nav>
    <div class="sidebar-bottom"><div class="account-card"><strong><?= e($user['name']) ?></strong><small>Administrator</small></div><a class="side-action" href="index.php?page=password">Change password</a><form method="post" action="index.php?page=logout"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><button class="side-action side-button">Logout</button></form></div>
</aside>
