<?php
$adminMenu = [
    'Dashboard' => ['dashboard'], 'Customers' => ['customers', 'customers-add'], 'Vehicles' => ['vehicles', 'vehicles-add'],
    'Job Cards' => ['jobcards-new', 'jobcards-pending', 'jobcards-ongoing', 'jobcards-completed'], 'Appointments' => ['appointments'], 'Estimates' => ['estimates'], 'Invoices' => ['invoices'], 'Payments' => ['payments'], 'Expenses' => ['expenses', 'expenses-categories'],
    'Stock / Parts' => ['stock', 'stock-add', 'stock-purchases', 'stock-low'], 'Services' => ['services'], 'Suppliers' => ['suppliers', 'suppliers-add'], 'Employees' => ['employees', 'employees-add', 'employees-salary', 'employees-advances', 'employees-loans', 'employees-attendance'], 'Other Income' => ['other-income'], 'Bay Management' => ['bays'],
    'Reports' => ['reports-daily', 'reports-gross-profit', 'reports-monthly', 'reports-sales', 'reports-payment', 'reports-expense', 'reports-other-income', 'reports-stock', 'reports-parts-purchase', 'reports-internal-external', 'reports-parts-profit', 'reports-discount', 'reports-outstanding', 'reports-employee', 'reports-net-profit'], 'User Management' => ['users-cashiers', 'users-add-cashier'], 'Settings' => ['settings-password'],
];
$labels = ['dashboard'=>'Dashboard','customers'=>'All Customers','customers-add'=>'Add Customer','vehicles'=>'All Vehicles','vehicles-add'=>'Add Vehicle','jobcards-new'=>'New Job Card','jobcards-pending'=>'Pending Job Cards','jobcards-ongoing'=>'Ongoing Job Cards','jobcards-completed'=>'Completed Job Cards','appointments'=>'Appointments','estimates'=>'Estimates','invoices'=>'Invoices','payments'=>'Payments','expenses'=>'Expense List','expenses-categories'=>'Expense Categories','stock'=>'Stock List','stock-add'=>'Add Stock','stock-purchases'=>'Stock Purchases','stock-low'=>'Low Stock','services'=>'Services','suppliers'=>'All Suppliers','suppliers-add'=>'Add Supplier','employees'=>'Employee List','employees-add'=>'Add Employee','employees-salary'=>'Salary Management','employees-advances'=>'Staff Advances','employees-loans'=>'Staff Loans','employees-attendance'=>'Attendance','other-income'=>'Other Income','bays'=>'Bay Management','users-cashiers'=>'Cashier Accounts','users-add-cashier'=>'Add Cashier','settings-password'=>'Change Password'];
?><aside class="sidebar admin-sidebar" data-sidebar>
    <div class="brand"><div class="brand-mark">DM</div><div><strong>DESHAPRIYA<br>MOTORS</strong><small>Garage management system</small></div></div>
    <nav class="sidebar-nav"><span class="nav-label">Main menu</span><?php foreach ($adminMenu as $group => $items): ?><?php if (count($items) === 1): ?><a class="nav-link <?= $section === $items[0] ? 'active' : '' ?>" href="index.php?page=admin&amp;section=<?= e($items[0]) ?>"><?= e($group) ?></a><?php else: ?><details class="nav-group" <?= in_array($section, $items, true) ? 'open' : '' ?>><summary><?= e($group) ?></summary><?php foreach ($items as $item): ?><a class="nav-sublink <?= $section === $item ? 'active' : '' ?>" href="index.php?page=admin&amp;section=<?= e($item) ?>"><?= e($labels[$item] ?? $item) ?></a><?php endforeach; ?></details><?php endif; ?><?php endforeach; ?></nav>
    <div class="sidebar-bottom"><div class="account-card"><strong><?= e($user['name']) ?></strong><small>Administrator</small></div><a class="side-action" href="index.php?page=password">Change password</a><form method="post" action="index.php?page=logout"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><button class="side-action side-button">Logout</button></form></div>
</aside>
