<?php

declare(strict_types=1);

function ensure_estimates_table(): void
{
    static $ready = false;
    if ($ready) return;
    ensure_customers_table();
    ensure_vehicles_table();
    ensure_vehicle_columns();
    database()->exec("CREATE TABLE IF NOT EXISTS estimates (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, estimate_no VARCHAR(30) NOT NULL, customer_id BIGINT UNSIGNED NOT NULL, vehicle_id BIGINT UNSIGNED NULL, mileage DECIMAL(12,2) NULL, engine_number VARCHAR(100) NULL, chassis_number VARCHAR(100) NULL, estimate_date DATE NOT NULL, valid_until DATE NOT NULL, service_type VARCHAR(190) NOT NULL, notes TEXT NULL, subtotal DECIMAL(12,2) NOT NULL DEFAULT 0, service_charge DECIMAL(12,2) NOT NULL DEFAULT 0, discount DECIMAL(12,2) NOT NULL DEFAULT 0, vat_rate DECIMAL(5,2) NOT NULL DEFAULT 18, vat_amount DECIMAL(12,2) NOT NULL DEFAULT 0, total_amount DECIMAL(12,2) NOT NULL DEFAULT 0, status ENUM('pending','accepted','rejected','expired') NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY estimates_no_unique (estimate_no), KEY estimates_customer_index (customer_id), KEY estimates_vehicle_index (vehicle_id), KEY estimates_date_index (estimate_date), KEY estimates_status_index (status), CONSTRAINT estimates_customer_fk FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE, CONSTRAINT estimates_vehicle_fk FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    database()->exec("CREATE TABLE IF NOT EXISTS estimate_items (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, estimate_id BIGINT UNSIGNED NOT NULL, item_name VARCHAR(190) NOT NULL, quantity DECIMAL(12,2) NOT NULL DEFAULT 1, unit_price DECIMAL(12,2) NOT NULL DEFAULT 0, amount DECIMAL(12,2) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id), KEY estimate_items_estimate_index (estimate_id), CONSTRAINT estimate_items_estimate_fk FOREIGN KEY (estimate_id) REFERENCES estimates (id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    try { database()->exec("ALTER TABLE estimates ADD COLUMN service_charge DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER subtotal"); } catch (Throwable $exception) { }
    $ready = true;
}

function estimate_customers(): array { return database()->query("SELECT id, name, customer_code, contact_number FROM customers WHERE status = 'active' ORDER BY name")->fetchAll(); }
function estimate_vehicles(): array { return database()->query("SELECT v.id, v.customer_id, v.vehicle_number, v.vehicle_type, v.make, v.model, v.current_mileage, v.engine_number, v.chassis_number FROM vehicles v JOIN customers c ON c.id=v.customer_id WHERE c.status='active' AND COALESCE(v.status,'active')='active' ORDER BY v.vehicle_number")->fetchAll(); }
function estimate_catalog(): array { $parts=[]; try { $parts=database()->query("SELECT id, product_name AS name, selling_price AS price, 'Spare Part' AS kind FROM supplier_products WHERE selling_price >= 0 ORDER BY product_name")->fetchAll(); } catch (Throwable $exception) { $parts=[]; } $services=[]; foreach (['Full Service','Oil Change','Brake Service','Engine Repair','AC Service','Wheel Alignment','Labour Charge'] as $name) $services[]=['id'=>0,'name'=>$name,'price'=>0,'kind'=>'Garage Service']; return array_merge($parts,$services); }
function estimate_items(int $id): array { $s=database()->prepare('SELECT * FROM estimate_items WHERE estimate_id=:id ORDER BY id'); $s->execute(['id'=>$id]); return $s->fetchAll(); }
function estimate_record(int $id): ?array { $s=database()->prepare('SELECT e.*,c.name customer_name,c.contact_number,v.vehicle_number,v.make,v.model FROM estimates e JOIN customers c ON c.id=e.customer_id LEFT JOIN vehicles v ON v.id=e.vehicle_id WHERE e.id=:id LIMIT 1'); $s->execute(['id'=>$id]); $row=$s->fetch(); if(!$row)return null; $row['items']=estimate_items($id); return $row; }
function estimate_filters(): array { $statuses=['pending','accepted','rejected','expired']; $valid=static fn($v):string=>preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)$v)?(string)$v:''; return ['search'=>trim((string)($_GET['search']??'')),'status'=>in_array($_GET['status']??'', $statuses,true)?$_GET['status']:'','customer_id'=>max(0,(int)($_GET['customer_id']??0)),'from'=>$valid($_GET['from']??''),'to'=>$valid($_GET['to']??'')]; }
function estimate_rows(array $f): array { $where=[];$p=[];if($f['search']!==''){$where[]='(e.estimate_no LIKE :q OR c.name LIKE :q OR v.vehicle_number LIKE :q OR e.service_type LIKE :q)';$p['q']='%'.$f['search'].'%';}if($f['status']!==''){$where[]='e.status=:status';$p['status']=$f['status'];}if($f['customer_id']>0){$where[]='e.customer_id=:customer_id';$p['customer_id']=$f['customer_id'];}if($f['from']!==''){$where[]='e.estimate_date>=:from_date';$p['from_date']=$f['from'];}if($f['to']!==''){$where[]='e.estimate_date<=:to_date';$p['to_date']=$f['to'];}$sql="SELECT e.*,c.name customer_name,c.contact_number,v.vehicle_number,v.make,v.model FROM estimates e JOIN customers c ON c.id=e.customer_id LEFT JOIN vehicles v ON v.id=e.vehicle_id".($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY e.estimate_date DESC,e.id DESC';$s=database()->prepare($sql);$s->execute($p);return $s->fetchAll(); }
function estimate_summary(): array { $r=database()->query("SELECT COUNT(*) total,SUM(status='pending') pending,SUM(status='accepted') accepted,SUM(status='rejected') rejected FROM estimates")->fetch()?:[];return ['total'=>(int)($r['total']??0),'pending'=>(int)($r['pending']??0),'accepted'=>(int)($r['accepted']??0),'rejected'=>(int)($r['rejected']??0)]; }
function close_expired_estimates(): void { database()->exec("UPDATE estimates SET status='expired' WHERE status='pending' AND valid_until < CURRENT_DATE"); }
function estimate_input(?array $source=null): array { $source??=$_POST;$items=[];foreach((array)($source['items']??[]) as $item){$name=trim((string)($item['name']??$item['item_name']??''));if($name!==''||(float)($item['quantity']??0)>0||(float)($item['unit_price']??0)>0)$items[]=['name'=>$name,'quantity'=>(string)($item['quantity']??'1'),'unit_price'=>(string)($item['unit_price']??'0')];}return ['customer_id'=>max(0,(int)($source['customer_id']??0)),'vehicle_id'=>max(0,(int)($source['vehicle_id']??0)),'mileage'=>trim((string)($source['mileage']??'')),'engine_number'=>trim((string)($source['engine_number']??'')),'chassis_number'=>trim((string)($source['chassis_number']??'')),'estimate_date'=>trim((string)($source['estimate_date']??date('Y-m-d'))),'valid_until'=>trim((string)($source['valid_until']??date('Y-m-d',strtotime('+30 days')))),'service_type'=>trim((string)($source['service_type']??'')),'notes'=>trim((string)($source['notes']??'')),'service_charge'=>(string)($source['service_charge']??'0'),'discount'=>(string)($source['discount']??'0'),'vat_rate'=>(string)($source['vat_rate']??'18'),'status'=>in_array($source['status']??'', ['pending','accepted','rejected','expired'],true)?$source['status']:'pending','items'=>$items]; }
function estimate_vehicle_registration_input(?array $source=null): array { $source??=$_POST; $vehicle=(array)($source['register_vehicle']??[]); return ['enabled'=>!empty($source['register_new_vehicle']),'vehicle_number'=>trim((string)($vehicle['vehicle_number']??'')),'vehicle_type'=>trim((string)($vehicle['vehicle_type']??'Car')),'make'=>trim((string)($vehicle['make']??'')),'model'=>trim((string)($vehicle['model']??''))]; }
function validate_estimate(array $i): array { $e=[];$date=DateTime::createFromFormat('Y-m-d',$i['estimate_date']);$valid=DateTime::createFromFormat('Y-m-d',$i['valid_until']);if($i['customer_id']<1)$e[]='Select a customer.';if(!$date||$date->format('Y-m-d')!==$i['estimate_date'])$e[]='Select a valid estimate date.';if(!$valid||$valid->format('Y-m-d')!==$i['valid_until'])$e[]='Select a valid valid-until date.';if($valid&&$date&&$valid<$date)$e[]='Valid until date cannot be before estimate date.';if($i['service_type']==='')$e[]='Service type or issue is required.';if(!$i['items'])$e[]='Add at least one estimate item.';foreach($i['items'] as $n=>$item){if($item['name']==='')$e[]='Item '.($n+1).' name is required.';if((float)$item['quantity']<=0)$e[]='Item '.($n+1).' quantity must be greater than zero.';if((float)$item['unit_price']<0)$e[]='Item '.($n+1).' price cannot be negative.';}if((float)$i['service_charge']<0||(float)$i['discount']<0||(float)$i['vat_rate']<0)$e[]='Service charge, discount and VAT cannot be negative.';return $e; }

function handle_estimate_request(string $section): void
{
    ensure_estimates_table(); close_expired_estimates();
    $id=max(0,(int)($_GET['id']??$_POST['estimate_id']??0)); $errors=[]; $input=estimate_input(); $registerVehicle=estimate_vehicle_registration_input();
    if($section==='estimates-add'&&$_SERVER['REQUEST_METHOD']!=='POST'&&!$input['items']) $input['items']=[['name'=>'','quantity'=>'1','unit_price'=>'0'],['name'=>'','quantity'=>'1','unit_price'=>'0']];
    if($section==='estimates-print-settings') { $settings=receipt_settings(); if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$values=['garage_name'=>trim((string)($_POST['garage_name']??'')),'tagline'=>trim((string)($_POST['tagline']??'')),'contact_number'=>trim((string)($_POST['contact_number']??'')),'email'=>trim((string)($_POST['email']??'')),'address'=>trim((string)($_POST['address']??'')),'receipt_header'=>trim((string)($_POST['receipt_header']??'')),'receipt_footer'=>trim((string)($_POST['receipt_footer']??''))];if($values['garage_name']==='')$errors[]='Garage name is required.';if(!$errors){$s=database()->prepare('UPDATE receipt_settings SET garage_name=:garage_name,tagline=:tagline,contact_number=:contact_number,email=:email,address=:address,receipt_header=:receipt_header,receipt_footer=:receipt_footer WHERE id=1');$s->execute($values);flash('success','Estimate print header and footer updated successfully.');redirect('index.php?page=admin&section=estimates-print-settings');}$settings=array_merge($settings,$values);}$title='Estimate Print Settings';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/estimate-print-settings.php';require __DIR__.'/../includes/footer.php';return; }
    if($section==='estimates-print') { $estimate=estimate_record($id);if(!$estimate){http_response_code(404);exit('Estimate not found.');}$estimatePrintSettings=receipt_settings();require __DIR__.'/../views/estimate-print.php';return; }
    if(in_array($section,['estimates-edit','estimates-view'],true)){ $estimate=estimate_record($id);if(!$estimate){http_response_code(404);exit('Estimate not found.');}if($section==='estimates-view'){$title='View Estimate';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/estimate-view-modal.php';require __DIR__.'/../includes/footer.php';return;}$input=estimate_input($estimate); }
    if($section==='estimates-delete'&&$_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$s=database()->prepare('DELETE FROM estimates WHERE id=:id');$s->execute(['id'=>$id]);flash('success','Estimate deleted successfully.');redirect('index.php?page=admin&section=estimates');}
    if($section==='estimates-status'&&$_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$status=$_POST['status']??'';if(in_array($status,['pending','accepted','rejected','expired'],true)){$s=database()->prepare('UPDATE estimates SET status=:status WHERE id=:id');$s->execute(['status'=>$status,'id'=>$id]);flash('success','Estimate status updated.');}redirect('index.php?page=admin&section=estimates');}
    if(in_array($section,['estimates-add','estimates-edit'],true)&&$_SERVER['REQUEST_METHOD']==='POST'){
        verify_csrf(); $input=estimate_input(); $registerVehicle=estimate_vehicle_registration_input(); $errors=validate_estimate($input);
        if($registerVehicle['enabled']){if($input['customer_id']<1)$errors[]='Select a customer before registering a vehicle.';if($registerVehicle['vehicle_number']==='')$errors[]='Vehicle number is required for a new vehicle.';if($registerVehicle['model']==='')$errors[]='Vehicle model is required for a new vehicle.';}
        elseif($input['vehicle_id']>0){$vehicleCheck=database()->prepare('SELECT id FROM vehicles WHERE id=:id AND customer_id=:customer_id AND COALESCE(status,\'active\')=\'active\'');$vehicleCheck->execute(['id'=>$input['vehicle_id'],'customer_id'=>$input['customer_id']]);if(!$vehicleCheck->fetch())$errors[]='The selected vehicle does not belong to this customer.';}
        if(!$errors){$itemSubtotal=0;foreach($input['items'] as $item)$itemSubtotal+=(float)$item['quantity']*(float)$item['unit_price'];$serviceCharge=max(0,(float)$input['service_charge']);$subtotal=$itemSubtotal+$serviceCharge;$discount=min((float)$input['discount'],$subtotal);$vat=max(0,($subtotal-$discount)*(float)$input['vat_rate']/100);$values=['customer_id'=>$input['customer_id'],'vehicle_id'=>$input['vehicle_id']?:null,'mileage'=>$input['mileage']!==''?(float)$input['mileage']:null,'engine_number'=>$input['engine_number']?:null,'chassis_number'=>$input['chassis_number']?:null,'estimate_date'=>$input['estimate_date'],'valid_until'=>$input['valid_until'],'service_type'=>$input['service_type'],'notes'=>$input['notes']?:null,'subtotal'=>$subtotal,'service_charge'=>$serviceCharge,'discount'=>$discount,'vat_rate'=>(float)$input['vat_rate'],'vat_amount'=>$vat,'total_amount'=>$subtotal-$discount+$vat,'status'=>$input['status']];$pdo=database();$pdo->beginTransaction();try{if($registerVehicle['enabled']){$vehicleStatement=$pdo->prepare('INSERT INTO vehicles (customer_id,vehicle_number,vehicle_type,make,model,engine_number,chassis_number,current_mileage) VALUES (:customer_id,:vehicle_number,:vehicle_type,:make,:model,:engine_number,:chassis_number,:current_mileage)');$vehicleStatement->execute(['customer_id'=>$input['customer_id'],'vehicle_number'=>$registerVehicle['vehicle_number'],'vehicle_type'=>$registerVehicle['vehicle_type']?:'Car','make'=>$registerVehicle['make']?:null,'model'=>$registerVehicle['model'],'engine_number'=>$input['engine_number']?:null,'chassis_number'=>$input['chassis_number']?:null,'current_mileage'=>$input['mileage']!==''?(float)$input['mileage']:null]);$values['vehicle_id']=(int)$pdo->lastInsertId();}elseif($input['vehicle_id']>0){$vehicleStatement=$pdo->prepare('UPDATE vehicles SET current_mileage=:current_mileage,engine_number=:engine_number,chassis_number=:chassis_number WHERE id=:id AND customer_id=:customer_id');$vehicleStatement->execute(['current_mileage'=>$input['mileage']!==''?(float)$input['mileage']:null,'engine_number'=>$input['engine_number']?:null,'chassis_number'=>$input['chassis_number']?:null,'id'=>$input['vehicle_id'],'customer_id'=>$input['customer_id']]);}$values['vehicle_id']=$values['vehicle_id']?:null;
            if($section==='estimates-add'){$s=$pdo->prepare('INSERT INTO estimates (estimate_no,customer_id,vehicle_id,mileage,engine_number,chassis_number,estimate_date,valid_until,service_type,notes,subtotal,service_charge,discount,vat_rate,vat_amount,total_amount,status) VALUES (:estimate_no,:customer_id,:vehicle_id,:mileage,:engine_number,:chassis_number,:estimate_date,:valid_until,:service_type,:notes,:subtotal,:service_charge,:discount,:vat_rate,:vat_amount,:total_amount,:status)');$s->execute(array_merge(['estimate_no'=>'TMP-'.bin2hex(random_bytes(4))],$values));$savedId=(int)$pdo->lastInsertId();$s=$pdo->prepare('UPDATE estimates SET estimate_no=:estimate_no WHERE id=:id');$s->execute(['estimate_no'=>'EST-'.date('ymd').'-'.str_pad((string)$savedId,4,'0',STR_PAD_LEFT),'id'=>$savedId]);}else{$values['id']=$id;$s=$pdo->prepare('UPDATE estimates SET customer_id=:customer_id,vehicle_id=:vehicle_id,mileage=:mileage,engine_number=:engine_number,chassis_number=:chassis_number,estimate_date=:estimate_date,valid_until=:valid_until,service_type=:service_type,notes=:notes,subtotal=:subtotal,service_charge=:service_charge,discount=:discount,vat_rate=:vat_rate,vat_amount=:vat_amount,total_amount=:total_amount,status=:status WHERE id=:id');$s->execute($values);$savedId=$id;$pdo->prepare('DELETE FROM estimate_items WHERE estimate_id=:id')->execute(['id'=>$id]);}$itemStatement=$pdo->prepare('INSERT INTO estimate_items (estimate_id,item_name,quantity,unit_price,amount) VALUES (:estimate_id,:item_name,:quantity,:unit_price,:amount)');foreach($input['items'] as $item)$itemStatement->execute(['estimate_id'=>$savedId,'item_name'=>$item['name'],'quantity'=>(float)$item['quantity'],'unit_price'=>(float)$item['unit_price'],'amount'=>(float)$item['quantity']*(float)$item['unit_price']]);$pdo->commit();flash('success',$section==='estimates-add'?'Estimate added successfully.':'Estimate updated successfully.');redirect('index.php?page=admin&section=estimates-print&id='.$savedId);}catch(Throwable $exception){if($pdo->inTransaction())$pdo->rollBack();$errors[]='The estimate and vehicle could not be saved. Check whether the vehicle number already exists.';}}
    }
    if(in_array($section,['estimates-add','estimates-edit'],true)){$customers=estimate_customers();$vehicles=estimate_vehicles();$catalog=estimate_catalog();$title=$section==='estimates-edit'?'Edit Estimate':'Create Estimate';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/estimate-form.php';require __DIR__.'/../includes/footer.php';return;}
    $filters=estimate_filters();$rows=estimate_rows($filters);$summary=estimate_summary();$customers=estimate_customers();$title='Estimates';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/estimates.php';require __DIR__.'/../includes/footer.php';
}
