<?php

declare(strict_types=1);

function ensure_job_cards_tables(): void
{
    database()->exec("CREATE TABLE IF NOT EXISTS job_cards (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, job_card_no VARCHAR(30) NOT NULL, customer_id BIGINT UNSIGNED NOT NULL, vehicle_id BIGINT UNSIGNED NOT NULL, complaint TEXT NULL, requested_work TEXT NULL, bay VARCHAR(60) NOT NULL, expected_delivery_date DATE NOT NULL, priority ENUM('low','normal','high') NOT NULL DEFAULT 'normal', mechanic VARCHAR(120) NULL, notes TEXT NULL, status ENUM('pending','ongoing','completed','cancelled') NOT NULL DEFAULT 'pending', created_by BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, started_at DATETIME NULL, completed_at DATETIME NULL, PRIMARY KEY (id), UNIQUE KEY job_cards_no_unique (job_card_no), KEY job_cards_customer_index (customer_id), KEY job_cards_vehicle_index (vehicle_id), KEY job_cards_status_index (status), CONSTRAINT job_cards_customer_fk FOREIGN KEY (customer_id) REFERENCES customers (id), CONSTRAINT job_cards_vehicle_fk FOREIGN KEY (vehicle_id) REFERENCES vehicles (id), CONSTRAINT job_cards_user_fk FOREIGN KEY (created_by) REFERENCES users (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    database()->exec("CREATE TABLE IF NOT EXISTS job_card_services (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, job_card_id BIGINT UNSIGNED NOT NULL, service_name VARCHAR(160) NOT NULL, notes TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id), KEY job_card_services_job_index (job_card_id), CONSTRAINT job_card_services_job_fk FOREIGN KEY (job_card_id) REFERENCES job_cards (id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    database()->exec("CREATE TABLE IF NOT EXISTS job_card_items (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, job_card_id BIGINT UNSIGNED NOT NULL, item_type ENUM('part','service') NOT NULL DEFAULT 'part', item_name VARCHAR(160) NOT NULL, item_code VARCHAR(60) NULL, quantity DECIMAL(12,2) NOT NULL DEFAULT 1, unit_price DECIMAL(12,2) NOT NULL DEFAULT 0, discount DECIMAL(12,2) NOT NULL DEFAULT 0, amount DECIMAL(12,2) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id), KEY job_card_items_job_index (job_card_id), CONSTRAINT job_card_items_job_fk FOREIGN KEY (job_card_id) REFERENCES job_cards (id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
}

function job_card_vehicles(): array { return database()->query("SELECT v.id, v.vehicle_number, v.vehicle_type, v.make, v.model, v.colour, v.year, v.current_mileage, c.id customer_id, c.name customer_name, c.contact_number, c.email, c.address FROM vehicles v INNER JOIN customers c ON c.id = v.customer_id WHERE v.status = 'active' AND c.status = 'active' ORDER BY v.vehicle_number ASC")->fetchAll(); }
function job_card_input(): array { return ['vehicle_id'=>(int) ($_POST['vehicle_id'] ?? 0), 'complaint'=>trim((string) ($_POST['complaint'] ?? '')), 'requested_work'=>trim((string) ($_POST['requested_work'] ?? '')), 'bay'=>trim((string) ($_POST['bay'] ?? '')), 'expected_delivery_date'=>trim((string) ($_POST['expected_delivery_date'] ?? date('Y-m-d'))), 'priority'=>$_POST['priority'] ?? 'normal', 'mechanic'=>trim((string) ($_POST['mechanic'] ?? '')), 'notes'=>trim((string) ($_POST['notes'] ?? '')), 'services'=>is_array($_POST['services'] ?? null) ? $_POST['services'] : [], 'items'=>is_array($_POST['items'] ?? null) ? $_POST['items'] : []]; }
function job_card_validation(array $input, array $vehicles): array { $errors = []; $vehicleIds = array_map('intval', array_column($vehicles, 'id')); if (!in_array($input['vehicle_id'], $vehicleIds, true)) $errors[] = 'Select a valid vehicle or customer.'; if ($input['bay'] === '') $errors[] = 'Working bay is required.'; if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $input['expected_delivery_date'])) $errors[] = 'Expected delivery date is required.'; if (!in_array($input['priority'], ['low','normal','high'], true)) $errors[] = 'Select a valid priority.'; foreach ($input['services'] as $index => $service) { $name = trim((string) ($service['name'] ?? '')); $notes = trim((string) ($service['notes'] ?? '')); if ($name === '' && $notes === '') continue; if ($name === '') $errors[] = 'Service ' . ($index + 1) . ' must have a name.'; } foreach ($input['items'] as $index => $item) { $name = trim((string) ($item['name'] ?? '')); if ($name === '') continue; if ((float) ($item['quantity'] ?? 0) <= 0) $errors[] = 'Item ' . ($index + 1) . ' quantity must be greater than zero.'; } return $errors; }
function job_card_list(string $status): array { $statement = database()->prepare("SELECT j.*, c.name customer_name, c.contact_number, v.vehicle_number, v.vehicle_type, v.make, v.model, v.current_mileage FROM job_cards j INNER JOIN customers c ON c.id = j.customer_id INNER JOIN vehicles v ON v.id = j.vehicle_id WHERE j.status = :status ORDER BY j.id DESC"); $statement->execute(['status'=>$status]); return $statement->fetchAll(); }
function job_card_vehicle(array $vehicles, int $id): ?array { foreach ($vehicles as $vehicle) if ((int) $vehicle['id'] === $id) return $vehicle; return null; }

function handle_job_card_request(string $section): void
{
    ensure_customers_table(); ensure_vehicles_table(); ensure_job_cards_tables(); $vehicles = job_card_vehicles(); $input = job_card_input(); $errors = [];
    if ($section === 'jobcards-new' && $_SERVER['REQUEST_METHOD'] === 'POST') { verify_csrf(); $errors = job_card_validation($input, $vehicles); if (!$errors) { $vehicle = job_card_vehicle($vehicles, $input['vehicle_id']); $pdo = database(); $pdo->beginTransaction(); try { $statement = $pdo->prepare('INSERT INTO job_cards (job_card_no,customer_id,vehicle_id,complaint,requested_work,bay,expected_delivery_date,priority,mechanic,notes,created_by) VALUES (:number,:customer_id,:vehicle_id,:complaint,:requested_work,:bay,:delivery,:priority,:mechanic,:notes,:created_by)'); $statement->execute(['number'=>'TMP-'.bin2hex(random_bytes(6)),'customer_id'=>$vehicle['customer_id'],'vehicle_id'=>$vehicle['id'],'complaint'=>$input['complaint'] ?: null,'requested_work'=>$input['requested_work'] ?: null,'bay'=>$input['bay'],'delivery'=>$input['expected_delivery_date'],'priority'=>$input['priority'],'mechanic'=>$input['mechanic'] ?: null,'notes'=>$input['notes'] ?: null,'created_by'=>current_user()['id']]); $id=(int) $pdo->lastInsertId(); $update=$pdo->prepare('UPDATE job_cards SET job_card_no=:number WHERE id=:id'); $update->execute(['number'=>'JC-'.date('ym').'-'.str_pad((string) $id, 5, '0', STR_PAD_LEFT),'id'=>$id]); $serviceStatement=$pdo->prepare('INSERT INTO job_card_services (job_card_id,service_name,notes) VALUES (:job,:name,:notes)'); foreach ($input['services'] as $service) { $name=trim((string) ($service['name'] ?? '')); if ($name !== '') $serviceStatement->execute(['job'=>$id,'name'=>$name,'notes'=>trim((string) ($service['notes'] ?? '')) ?: null]); } $itemStatement=$pdo->prepare('INSERT INTO job_card_items (job_card_id,item_type,item_name,item_code,quantity,unit_price,discount,amount) VALUES (:job,:type,:name,:code,:quantity,:price,:discount,:amount)'); foreach ($input['items'] as $item) { $name=trim((string) ($item['name'] ?? '')); if ($name === '') continue; $quantity=(float) ($item['quantity'] ?? 1); $price=(float) ($item['unit_price'] ?? 0); $discount=(float) ($item['discount'] ?? 0); $itemStatement->execute(['job'=>$id,'type'=>in_array($item['type'] ?? '', ['part','service'], true) ? $item['type'] : 'part','name'=>$name,'code'=>trim((string) ($item['code'] ?? '')) ?: null,'quantity'=>$quantity,'price'=>$price,'discount'=>$discount,'amount'=>max(0, ($quantity*$price)-$discount)]); } $pdo->commit(); flash('success','Job card created successfully.'); redirect('index.php?page=admin&section=jobcards-pending'); } catch (Throwable $exception) { if ($pdo->inTransaction()) $pdo->rollBack(); $errors[]='The job card could not be saved.'; } } }
    $status = ['jobcards-pending'=>'pending','jobcards-ongoing'=>'ongoing','jobcards-completed'=>'completed'][$section] ?? null; $rows = $status ? job_card_list($status) : [];
    $title = $section === 'jobcards-new' ? 'New Job Card' : ucfirst((string) $status) . ' Job Cards'; $sectionForHeader = $section; $section = $sectionForHeader;
    require __DIR__ . '/../includes/header.php'; require __DIR__ . '/../views/' . ($section === 'jobcards-new' ? 'jobcard-new.php' : 'jobcards.php'); require __DIR__ . '/../includes/footer.php';
}
