<?php
declare(strict_types=1);

function ensure_service_tables(): void
{
    static $ready=false;if($ready)return;$pdo=database();
    $pdo->exec("CREATE TABLE IF NOT EXISTS service_categories (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,category_name VARCHAR(100) NOT NULL,status ENUM('active','inactive') NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY service_categories_name_unique(category_name),KEY service_categories_status_index(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $pdo->exec("CREATE TABLE IF NOT EXISTS services (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,service_code VARCHAR(30) NOT NULL,service_name VARCHAR(190) NOT NULL,service_category_id BIGINT UNSIGNED NULL,description TEXT NULL,price DECIMAL(12,2) NOT NULL DEFAULT 0,duration_minutes INT UNSIGNED NULL,status ENUM('active','inactive') NOT NULL DEFAULT 'active',created_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY services_code_unique(service_code),KEY services_name_index(service_name),KEY services_category_index(service_category_id),KEY services_status_index(status),CONSTRAINT services_category_fk FOREIGN KEY(service_category_id) REFERENCES service_categories(id) ON DELETE SET NULL,CONSTRAINT services_user_fk FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $pdo->exec("INSERT IGNORE INTO service_categories(category_name) VALUES ('Engine'),('Brakes'),('Electrical'),('Suspension'),('Tires'),('Transmission'),('Cleaning'),('General'),('AC'),('Other')");
    $ready=true;
}
function service_categories():array{return database()->query("SELECT * FROM service_categories WHERE status='active' ORDER BY category_name")->fetchAll();}
function service_category_id(string $name):int{$s=database()->prepare('SELECT id FROM service_categories WHERE category_name=:name AND status=:status');$s->execute(['name'=>$name,'status'=>'active']);return (int)($s->fetchColumn()?:0);}
function service_input(?array $source=null):array{$source??=$_POST;$category=$source['category_id']??$source['service_category_id']??0;return ['service_name'=>trim((string)($source['service_name']??'')),'category_id'=>max(0,(int)$category),'description'=>trim((string)($source['description']??'')),'price'=>(string)($source['price']??'0'),'duration'=>trim((string)($source['duration_minutes']??$source['duration']??'')),'status'=>($source['status']??'active')==='inactive'?'inactive':'active'];}
function service_code():string{$n=(int)database()->query('SELECT COALESCE(MAX(id),0)+1 FROM services')->fetchColumn();return 'SRV-'.str_pad((string)$n,3,'0',STR_PAD_LEFT);}
function service_summary():array{$r=database()->query("SELECT COUNT(*) total,SUM(status='active') active,SUM(status='inactive') inactive,COALESCE(AVG(CASE WHEN status='active' THEN price END),0) average_price FROM services")->fetch()?:[];return ['total'=>(int)($r['total']??0),'active'=>(int)($r['active']??0),'inactive'=>(int)($r['inactive']??0),'average_price'=>(float)($r['average_price']??0)];}
function service_rows(array $f):array{$where=[];$p=[];if($f['search']!==''){$where[]='(s.service_code LIKE :q OR s.service_name LIKE :q OR s.description LIKE :q)';$p['q']='%'.$f['search'].'%';}if($f['category_id']>0){$where[]='s.service_category_id=:category_id';$p['category_id']=$f['category_id'];}if($f['status']!==''){$where[]='s.status=:status';$p['status']=$f['status'];}$limit=$f['per_page'];$offset=($f['page']-1)*$limit;$base=' FROM services s LEFT JOIN service_categories c ON c.id=s.service_category_id'.($where?' WHERE '.implode(' AND ',$where):'');$count=database()->prepare('SELECT COUNT(*)'.$base);$count->execute($p);$total=(int)$count->fetchColumn();$stmt=database()->prepare('SELECT s.*,c.category_name'.$base.' ORDER BY s.id DESC LIMIT '.$limit.' OFFSET '.$offset);$stmt->execute($p);return [$stmt->fetchAll(),$total];}
function service_record(int $id):?array{$s=database()->prepare('SELECT s.*,c.category_name FROM services s LEFT JOIN service_categories c ON c.id=s.service_category_id WHERE s.id=:id');$s->execute(['id'=>$id]);return $s->fetch()?:null;}
function service_validate(array $i):array{$e=[];if($i['service_name']==='')$e[]='Service name is required.';if($i['category_id']<1)$e[]='Select a service category.';if((float)$i['price']<0)$e[]='Price cannot be negative.';$duration=$i['duration'];if($duration!==''&&!ctype_digit($duration))$e[]='Duration must be a valid positive number.';return $e;}
function handle_service_request(string $section):void{
    ensure_service_tables();$id=max(0,(int)($_GET['id']??$_POST['service_id']??0));$errors=[];
    if($section==='services-category-add'){if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$name=trim((string)($_POST['category_name']??''));if($name==='')$errors[]='Category name is required.';if(!$errors){try{database()->prepare('INSERT INTO service_categories(category_name) VALUES(:name)')->execute(['name'=>$name]);flash('success','Service category added successfully.');redirect('index.php?page=admin&section=services');}catch(Throwable $e){$errors[]='Category already exists.';}}}$category_name=$name??'';$title='Add Service Category';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/service-category-form.php';require __DIR__.'/../includes/footer.php';return;}
    if($section==='services-view'){$service=service_record($id);if(!$service){http_response_code(404);exit('Service not found.');}$title='View Service';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/service-view.php';require __DIR__.'/../includes/footer.php';return;}
    if($section==='services-toggle'&&$_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();database()->prepare("UPDATE services SET status=IF(status='active','inactive','active') WHERE id=:id")->execute(['id'=>$id]);flash('success','Service status updated.');redirect('index.php?page=admin&section=services');}
    if($section==='services-delete'&&$_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();database()->prepare('DELETE FROM services WHERE id=:id')->execute(['id'=>$id]);flash('success','Service removed successfully.');redirect('index.php?page=admin&section=services');}
    $editing=$section==='services-edit';$service=$editing?service_record($id):null;if($editing&&!$service){http_response_code(404);exit('Service not found.');}
    $input=service_input($editing?$service:null);
    if(in_array($section,['services-add','services-edit'],true)&&$_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$input=service_input();$errors=service_validate($input);if(!$errors){$pdo=database();try{if($editing){$pdo->prepare('UPDATE services SET service_name=:name,service_category_id=:category,description=:description,price=:price,duration_minutes=:duration,status=:status WHERE id=:id')->execute(['name'=>$input['service_name'],'category'=>$input['category_id']?:null,'description'=>$input['description']?:null,'price'=>(float)$input['price'],'duration'=>$input['duration']!==''?(int)$input['duration']:null,'status'=>$input['status'],'id'=>$id]);flash('success','Service updated successfully.');}else{$pdo->prepare('INSERT INTO services(service_code,service_name,service_category_id,description,price,duration_minutes,status,created_by) VALUES(:code,:name,:category,:description,:price,:duration,:status,:user)')->execute(['code'=>service_code(),'name'=>$input['service_name'],'category'=>$input['category_id']?:null,'description'=>$input['description']?:null,'price'=>(float)$input['price'],'duration'=>$input['duration']!==''?(int)$input['duration']:null,'status'=>$input['status'],'user'=>current_user()['id']??null]);flash('success','Service added successfully.');}redirect('index.php?page=admin&section=services');}catch(Throwable $e){$errors[]='Service code or service name already exists.';}}}
    if(in_array($section,['services-add','services-edit'],true)){$categories=service_categories();$title=$editing?'Edit Service':'Add New Service';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/service-form.php';require __DIR__.'/../includes/footer.php';return;}
    $perPage=(int)($_GET['per_page']??10);if(!in_array($perPage,[10,25,50],true))$perPage=10;$filters=['search'=>trim((string)($_GET['search']??'')),'category_id'=>max(0,(int)($_GET['category_id']??0)),'status'=>in_array($_GET['status']??'', ['active','inactive'],true)?$_GET['status']:'','page'=>max(1,(int)($_GET['page_no']??1)),'per_page'=>$perPage];[$rows,$total]=service_rows($filters);$summary=service_summary();$categories=service_categories();$pages=max(1,(int)ceil($total/$filters['per_page']));if($filters['page']>$pages)$filters['page']=$pages;$title='Services';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/services.php';require __DIR__.'/../includes/footer.php';
}
