<?php
declare(strict_types=1);

function ensure_stock_tables(): void
{
    static $ready=false; if($ready)return; $pdo=database();
    $pdo->exec("CREATE TABLE IF NOT EXISTS stock_items (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,part_code VARCHAR(60) NOT NULL,part_name VARCHAR(190) NOT NULL,category VARCHAR(100) NULL,brand VARCHAR(100) NULL,unit VARCHAR(30) NOT NULL DEFAULT 'PCS',buying_price DECIMAL(12,2) NOT NULL DEFAULT 0,selling_price DECIMAL(12,2) NOT NULL DEFAULT 0,stock_qty DECIMAL(12,2) NOT NULL DEFAULT 0,reorder_level DECIMAL(12,2) NOT NULL DEFAULT 10,supplier_id BIGINT UNSIGNED NULL,status ENUM('active','inactive') NOT NULL DEFAULT 'active',notes TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY stock_items_code_unique(part_code)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $pdo->exec("CREATE TABLE IF NOT EXISTS stock_purchases (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,purchase_no VARCHAR(30) NOT NULL,supplier_id BIGINT UNSIGNED NULL,purchase_date DATE NOT NULL,invoice_no VARCHAR(80) NULL,payment_status ENUM('paid','partial','due') NOT NULL DEFAULT 'paid',total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0,balance_amount DECIMAL(12,2) NOT NULL DEFAULT 0,notes TEXT NULL,created_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY stock_purchases_no_unique(purchase_no)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $pdo->exec("CREATE TABLE IF NOT EXISTS stock_purchase_items (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,purchase_id BIGINT UNSIGNED NOT NULL,stock_item_id BIGINT UNSIGNED NOT NULL,quantity DECIMAL(12,2) NOT NULL,unit_cost DECIMAL(12,2) NOT NULL,amount DECIMAL(12,2) NOT NULL,PRIMARY KEY(id),KEY purchase_idx(purchase_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $pdo->exec("CREATE TABLE IF NOT EXISTS stock_batches (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,stock_item_id BIGINT UNSIGNED NOT NULL,stock_purchase_item_id BIGINT UNSIGNED NULL,quantity_received DECIMAL(12,2) NOT NULL,quantity_remaining DECIMAL(12,2) NOT NULL,buying_price DECIMAL(12,2) NOT NULL,selling_price_at_purchase DECIMAL(12,2) NULL,purchase_date DATE NOT NULL,supplier_id BIGINT UNSIGNED NULL,batch_reference VARCHAR(80) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY batch_stock_idx(stock_item_id),KEY batch_date_idx(purchase_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $pdo->exec("CREATE TABLE IF NOT EXISTS stock_movements (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,stock_item_id BIGINT UNSIGNED NOT NULL,movement_type VARCHAR(30) NOT NULL,quantity DECIMAL(12,2) NOT NULL,quantity_before DECIMAL(12,2) NOT NULL,quantity_after DECIMAL(12,2) NOT NULL,unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0,reference_type VARCHAR(40) NULL,reference_id BIGINT UNSIGNED NULL,notes TEXT NULL,created_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY movement_stock_idx(stock_item_id),KEY movement_date_idx(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    foreach(["ALTER TABLE stock_items ADD COLUMN supplier_id BIGINT UNSIGNED NULL","ALTER TABLE stock_purchases ADD COLUMN invoice_no VARCHAR(80) NULL","ALTER TABLE stock_purchases ADD COLUMN payment_status ENUM('paid','partial','due') NOT NULL DEFAULT 'paid'","ALTER TABLE stock_purchases ADD COLUMN paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0","ALTER TABLE stock_purchases ADD COLUMN balance_amount DECIMAL(12,2) NOT NULL DEFAULT 0","ALTER TABLE stock_purchases ADD COLUMN created_by BIGINT UNSIGNED NULL"] as $sql){try{$pdo->exec($sql);}catch(Throwable $e){}}
    $ready=true;
}
function stock_suppliers(): array { try{return database()->query("SELECT id,name,supplier_code FROM suppliers WHERE status='active' ORDER BY name")->fetchAll();}catch(Throwable $e){return [];} }
function stock_rows(bool $low=false): array { $where="si.status='active'".($low?' AND si.stock_qty<=si.reorder_level':'');$s=database()->query("SELECT si.*,s.name supplier_name,(SELECT COALESCE(SUM(b.quantity_remaining*b.buying_price),0)/NULLIF(SUM(b.quantity_remaining),0) FROM stock_batches b WHERE b.stock_item_id=si.id) average_cost FROM stock_items si LEFT JOIN suppliers s ON s.id=si.supplier_id WHERE $where ORDER BY si.part_name");return $s->fetchAll(); }
function stock_one(int $id): ?array { $s=database()->prepare('SELECT si.*,s.name supplier_name FROM stock_items si LEFT JOIN suppliers s ON s.id=si.supplier_id WHERE si.id=:id');$s->execute(['id'=>$id]);return $s->fetch()?:null; }
function stock_input(?array $src=null): array {$src??=$_POST;return ['part_code'=>trim((string)($src['part_code']??'')),'part_name'=>trim((string)($src['part_name']??'')),'category'=>trim((string)($src['category']??'')),'brand'=>trim((string)($src['brand']??'')),'unit'=>trim((string)($src['unit']??'PCS')),'buying_price'=>(float)($src['buying_price']??0),'selling_price'=>(float)($src['selling_price']??0),'stock_qty'=>(float)($src['stock_qty']??0),'reorder_level'=>(float)($src['reorder_level']??10),'supplier_id'=>max(0,(int)($src['supplier_id']??0)),'notes'=>trim((string)($src['notes']??''))];}
function stock_purchase_rows(): array {return database()->query('SELECT p.*,s.name supplier_name,(SELECT COUNT(*) FROM stock_purchase_items i WHERE i.purchase_id=p.id) item_count FROM stock_purchases p LEFT JOIN suppliers s ON s.id=p.supplier_id ORDER BY p.purchase_date DESC,p.id DESC')->fetchAll();}
function stock_batches(int $id): array {$s=database()->prepare('SELECT b.*,s.name supplier_name,p.invoice_no FROM stock_batches b LEFT JOIN suppliers s ON s.id=b.supplier_id LEFT JOIN stock_purchase_items pi ON pi.id=b.stock_purchase_item_id LEFT JOIN stock_purchases p ON p.id=pi.purchase_id WHERE b.stock_item_id=:id ORDER BY b.purchase_date,b.id');$s->execute(['id'=>$id]);return $s->fetchAll();}
function stock_movements(int $id): array {$s=database()->prepare('SELECT m.*,u.name user_name FROM stock_movements m LEFT JOIN users u ON u.id=m.created_by WHERE m.stock_item_id=:id ORDER BY m.id DESC');$s->execute(['id'=>$id]);return $s->fetchAll();}
function stock_save_new(array $i): void {$pdo=database();$pdo->beginTransaction();try{$s=$pdo->prepare('INSERT INTO stock_items(part_code,part_name,category,brand,unit,buying_price,selling_price,stock_qty,reorder_level,supplier_id,notes) VALUES(:part_code,:part_name,:category,:brand,:unit,:buying_price,:selling_price,:stock_qty,:reorder_level,:supplier_id,:notes)');$s->execute(['part_code'=>$i['part_code'],'part_name'=>$i['part_name'],'category'=>$i['category']?:null,'brand'=>$i['brand']?:null,'unit'=>$i['unit'],'buying_price'=>$i['buying_price'],'selling_price'=>$i['selling_price'],'stock_qty'=>$i['stock_qty'],'reorder_level'=>$i['reorder_level'],'supplier_id'=>$i['supplier_id']?:null,'notes'=>$i['notes']?:null]);$id=(int)$pdo->lastInsertId();if($i['stock_qty']>0){$s=$pdo->prepare('INSERT INTO stock_batches(stock_item_id,quantity_received,quantity_remaining,buying_price,selling_price_at_purchase,purchase_date,batch_reference) VALUES(:id,:qty,:qty,:cost,:sell,CURRENT_DATE,:ref)');$s->execute(['id'=>$id,'qty'=>$i['stock_qty'],'cost'=>$i['buying_price'],'sell'=>$i['selling_price'],'ref'=>'OPENING-'.$id]);$s=$pdo->prepare('INSERT INTO stock_movements(stock_item_id,movement_type,quantity,quantity_before,quantity_after,unit_cost,reference_type,reference_id,created_by) VALUES(:id,\'opening_stock\',:qty,0,:qty,:cost,\'stock_item\',:id,:user)');$s->execute(['id'=>$id,'qty'=>$i['stock_qty'],'cost'=>$i['buying_price'],'user'=>current_user()['id']??null]);}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
function stock_restock(array $i): void {$pdo=database();$pdo->beginTransaction();try{$s=$pdo->prepare('SELECT * FROM stock_items WHERE id=:id AND status=\'active\' FOR UPDATE');$s->execute(['id'=>$i['stock_item_id']]);$item=$s->fetch();if(!$item)throw new RuntimeException('Stock item not found.');$before=(float)$item['stock_qty'];$after=$before+$i['quantity'];$total=$i['quantity']*$i['buying_price'];$purchaseNo='PUR-'.date('ymdHis').'-'.random_int(10,99);$status=$i['payment_status'];$paid=$status==='paid'?$total:($status==='partial'?min($total,$i['paid_amount']):0);$s=$pdo->prepare('INSERT INTO stock_purchases(purchase_no,supplier_id,purchase_date,invoice_no,payment_status,total_amount,paid_amount,balance_amount,notes,created_by) VALUES(:no,:supplier,:date,:invoice,:status,:total,:paid,:balance,:notes,:user)');$s->execute(['no'=>$purchaseNo,'supplier'=>$i['supplier_id']?:null,'date'=>$i['purchase_date'],'invoice'=>$i['invoice_no']?:null,'status'=>$status,'total'=>$total,'paid'=>$paid,'balance'=>$total-$paid,'notes'=>$i['notes']?:null,'user'=>current_user()['id']??null]);$purchase=(int)$pdo->lastInsertId();$s=$pdo->prepare('INSERT INTO stock_purchase_items(purchase_id,stock_item_id,quantity,unit_cost,amount) VALUES(:purchase,:item,:qty,:cost,:amount)');$s->execute(['purchase'=>$purchase,'item'=>$item['id'],'qty'=>$i['quantity'],'cost'=>$i['buying_price'],'amount'=>$total]);$line=(int)$pdo->lastInsertId();$s=$pdo->prepare('INSERT INTO stock_batches(stock_item_id,stock_purchase_item_id,quantity_received,quantity_remaining,buying_price,selling_price_at_purchase,purchase_date,supplier_id,batch_reference) VALUES(:item,:line,:qty,:qty,:cost,:sell,:date,:supplier,:ref)');$s->execute(['item'=>$item['id'],'line'=>$line,'qty'=>$i['quantity'],'cost'=>$i['buying_price'],'sell'=>$i['selling_price'],'date'=>$i['purchase_date'],'supplier'=>$i['supplier_id']?:null,'ref'=>$purchaseNo]);$s=$pdo->prepare('UPDATE stock_items SET stock_qty=:after,buying_price=((buying_price* :before)+(:qty*:cost))/NULLIF(:after,0),selling_price=:sell WHERE id=:id');$s->execute(['after'=>$after,'before'=>$before,'qty'=>$i['quantity'],'cost'=>$i['buying_price'],'sell'=>$i['selling_price']>0?$i['selling_price']:$item['selling_price'],'id'=>$item['id']]);$s=$pdo->prepare('INSERT INTO stock_movements(stock_item_id,movement_type,quantity,quantity_before,quantity_after,unit_cost,reference_type,reference_id,notes,created_by) VALUES(:item,\'restock\',:qty,:before,:after,:cost,\'purchase\',:purchase,:notes,:user)');$s->execute(['item'=>$item['id'],'qty'=>$i['quantity'],'before'=>$before,'after'=>$after,'cost'=>$i['buying_price'],'purchase'=>$purchase,'notes'=>$i['notes']?:null,'user'=>current_user()['id']??null]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
function stock_consume_fifo(PDO $pdo,int $stockItemId,float $quantity): float { if($quantity<=0)throw new InvalidArgumentException('Quantity must be greater than zero.');$s=$pdo->prepare('SELECT * FROM stock_items WHERE id=:id AND status=\'active\' FOR UPDATE');$s->execute(['id'=>$stockItemId]);$item=$s->fetch();if(!$item||$quantity>(float)$item['stock_qty'])throw new RuntimeException('Insufficient stock.');$remaining=$quantity;$cost=0.0;$b=$pdo->prepare('SELECT * FROM stock_batches WHERE stock_item_id=:id AND quantity_remaining>0 ORDER BY purchase_date,id FOR UPDATE');$b->execute(['id'=>$stockItemId]);foreach($b->fetchAll() as $batch){if($remaining<=0)break;$used=min($remaining,(float)$batch['quantity_remaining']);$u=$pdo->prepare('UPDATE stock_batches SET quantity_remaining=quantity_remaining-:used WHERE id=:id');$u->execute(['used'=>$used,'id'=>$batch['id']]);$cost+=$used*(float)$batch['buying_price'];$remaining-=$used;}if($remaining>0)throw new RuntimeException('Stock batches are inconsistent.');$u=$pdo->prepare('UPDATE stock_items SET stock_qty=stock_qty-:qty WHERE id=:id');$u->execute(['qty'=>$quantity,'id'=>$stockItemId]);return $cost;}
function handle_stock_request(string $section): void { ensure_stock_tables();$id=max(0,(int)($_GET['id']??$_POST['id']??0));$errors=[];
    if($section==='stock-delete'&&$_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$s=database()->prepare("UPDATE stock_items SET status='inactive' WHERE id=:id");$s->execute(['id'=>$id]);flash('success','Stock item removed.');redirect('index.php?page=admin&section=stock');}
    if($section==='stock-add'&&$_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$i=stock_input();if($i['part_code']===''||$i['part_name']==='')$errors[]='Part code and part name are required.';if($i['stock_qty']<0||$i['buying_price']<0)$errors[]='Quantity and buying price cannot be negative.';if(!$errors)try{stock_save_new($i);flash('success','Stock item added successfully.');redirect('index.php?page=admin&section=stock');}catch(Throwable $e){$errors[]='Stock item could not be saved. Part code may already exist.';}}
    if($section==='stock-restock'&&$_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$i=['stock_item_id'=>$id?:max(0,(int)($_POST['stock_item_id']??0)),'quantity'=>(float)($_POST['quantity']??0),'buying_price'=>(float)($_POST['buying_price']??0),'selling_price'=>(float)($_POST['selling_price']??0),'supplier_id'=>max(0,(int)($_POST['supplier_id']??0)),'purchase_date'=>trim((string)($_POST['purchase_date']??date('Y-m-d'))),'invoice_no'=>trim((string)($_POST['invoice_no']??'')),'payment_status'=>in_array($_POST['payment_status']??'', ['paid','partial','due'],true)?$_POST['payment_status']:'paid','paid_amount'=>(float)($_POST['paid_amount']??0),'notes'=>trim((string)($_POST['notes']??''))];if($i['stock_item_id']<1||$i['quantity']<=0||$i['buying_price']<0)$errors[]='Select an item and enter valid quantity and buying price.';if(!$errors)try{stock_restock($i);flash('success','Stock restocked successfully.');redirect('index.php?page=admin&section=stock-purchases');}catch(Throwable $e){$errors[]='Restock could not be saved. Please try again.';}}
    if($section==='stock-view'){$item=stock_one($id);if(!$item){http_response_code(404);exit('Stock item not found.');}$batches=stock_batches($id);$movements=stock_movements($id);$title='View Stock Item';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/stock-view.php';require __DIR__.'/../includes/footer.php';return;}
    if($section==='stock-add'){$input=stock_input();$suppliers=stock_suppliers();$title='Add Stock';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/stock-form.php';require __DIR__.'/../includes/footer.php';return;}
    if($section==='stock-restock'){$item=stock_one($id);$suppliers=stock_suppliers();$title='Restock Item';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/stock-restock.php';require __DIR__.'/../includes/footer.php';return;}
    if($section==='stock-purchases'){$rows=stock_purchase_rows();$title='Stock Purchases';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/stock-purchases.php';require __DIR__.'/../includes/footer.php';return;}
    $rows=stock_rows($section==='stock-low');$title=$section==='stock-low'?'Low Stock':'Stock / Parts';$sectionForHeader=$section;require __DIR__.'/../includes/header.php';require __DIR__.'/../views/stock.php';require __DIR__.'/../includes/footer.php';
}
